# Canonical table contract extracted from Frahoosh_v16_12_LOGIN_BACKGROUND_FINAL_02.zip
# The uploaded ZIP is the source of truth for Android table columns.

ZIP_TABLE_FIELDS = {
    "students":["id","first_name","last_name","national_code","student_code","grade","class_name","phone","parent_phone","email","address"],
    "teachers":["id","first_name","last_name","national_code","phone","email","subject","grades"],
    "staff":["id","first_name","last_name","role","phone","employee_code","national_code","employment_status"],
    "attendance":["id","student_id","date","status","description"],
    "teacher_attendance":["id","student_id","teacher_id","class_name","subject","attendance_date","status","description"],
    "grades":["id","student_id","subject","exam_name","score","grade_type","term","grade_date"],
    "grade_items":["id","student_id","teacher_id","subject","grade_type","term","score","grade_date","description"],
    "student_grades":["id","student_id","subject","exam_name","score","grade_type","term","grade_date"],
    "assignments":["id","student_id","teacher","subject","title","due_date","status"],
    "educational_activities":["id","student_id","teacher_id","subject","title","activity_date","description"],
    "teacher_exams":["id","teacher_id","title","subject","grade","class_name","exam_type","exam_date","duration"],
    "lesson_plans":["id","teacher_id","teacher_name","subject","grade","class_name","title","content","session_date","created_at"],
    "teacher_meetings":["id","teacher_id","student_id","student_name","parent_name","meeting_at","subject","status","report"],
    "executive_classes":["id","name","grade","teacher","created_at"],
    "executive_operations":["id","operation_type","title","student_id","class_name","status","operation_date","description"],
    "executive_reports":["id","title","report_type","student_id","class_name","report_date","created_by"],
    "weekly_schedule":["id","teacher","hours","grade","class_count","subject","bell_pattern","class_names"],
    "exam_schedule":["id","subject","grade","exam_date","duration","weight"],
    "cultural_activity_registrations":["id","student_id","activity_id","activity_title","activity_kind","fee","payment_status","registration_date"],
    "competitions":["id","title","category","start_date","end_date","status"],
    "cultural_reports":["id","title","report_type","activity_id","report_date"],
    "payment_records":["id","student_id","parent_username","title","amount","status","payment_date"],
    "school_events":["id","event_type","title","actor_username","created_at"],
    "smart_board_content":["id","title","content","class_id","teacher_id","content_date_shamsi"],
    "smart_board_whiteboards":["id","title","content","class_id","teacher_id","board_date"],
    "smart_board_files":["id","title","file_path","file_type","class_id","teacher_id"],
    "smart_board_media":["id","title","media_path","media_type","class_id","teacher_id"],
    "smart_board_quizzes":["id","title","question","correct_option","class_id","teacher_id","quiz_date_shamsi"],
    "smart_board_activities":["id","title","activity_text","class_id","teacher_id","activity_date_shamsi"],
    "ai_assistant_sessions":["id","username","role","title","request_date_shamsi"],
    "ai_questions":["id","username","role","question","answer","answer_date_shamsi"],
    "ai_educational_analysis":["id","student_id","teacher_id","subject","period","score","risk_level","analysis_date_shamsi"],
    "ai_smart_reports":["id","title","report_type","target_type","target_id","created_by","report_date_shamsi"],
    "parent_children":["id","first_name","last_name","student_code","grade","class_name","parent_phone"],
    "parent_meeting_requests":["id","student_id","teacher_id","parent_phone","reason","meeting_date","status"],
}

ZIP_COLUMN_LABELS = {
    "id":"شناسه","first_name":"نام","last_name":"نام خانوادگی","national_code":"کد ملی","student_code":"کد دانش‌آموزی",
    "grade":"پایه","class_name":"کلاس","phone":"تلفن","parent_phone":"تلفن والد","email":"ایمیل","address":"آدرس",
    "teacher_id":"دبیر","student_id":"دانش‌آموز","student_name":"نام دانش‌آموز","parent_name":"ولی","parent_username":"ولی",
    "subject":"درس","title":"عنوان","description":"توضیحات","status":"وضعیت","date":"تاریخ","attendance_date":"تاریخ",
    "exam_name":"ارزشیابی","grade_type":"نوع نمره","term":"نوبت","score":"نمره","grade_date":"تاریخ","teacher":"دبیر",
    "due_date":"مهلت","activity_date":"تاریخ","operation_type":"نوع","operation_date":"تاریخ","report_type":"نوع",
    "created_by":"ثبت‌کننده","hours":"ساعت","class_count":"تعداد کلاس","bell_pattern":"زنگ","class_names":"کلاس‌ها",
    "exam_date":"تاریخ امتحان","duration":"مدت","weight":"ضریب","category":"دسته","start_date":"شروع","end_date":"پایان",
    "activity_id":"فعالیت","activity_title":"عنوان فعالیت","activity_kind":"نوع فعالیت","fee":"هزینه","payment_status":"پرداخت",
    "event_type":"نوع","actor_username":"فرستنده","report":"گزارش","meeting_at":"زمان","role":"نقش","employee_code":"کد پرسنلی",
    "employment_status":"وضعیت استخدام","content":"محتوا","content_date_shamsi":"تاریخ شمسی","board_date":"تاریخ",
    "file_path":"مسیر فایل","file_type":"نوع","media_path":"مسیر","media_type":"نوع","activity_text":"شرح",
    "quiz_date_shamsi":"تاریخ شمسی","username":"کاربر","question":"پرسش","answer":"پاسخ","answer_date_shamsi":"تاریخ شمسی",
    "period":"دوره","risk_level":"ریسک","analysis_date_shamsi":"تاریخ شمسی","target_type":"هدف","target_id":"شناسه هدف",
    "request_date_shamsi":"تاریخ شمسی","meeting_date":"تاریخ جلسه","name":"کلاس"
}
