# Canonical Android navigation/data contract derived from Frahoosh V16.12.
ROLE_NAMES = {
    "manager": "مدیریت",
    "admin": "مدیریت",
    "administrator": "مدیریت",
    "educational": "معاون آموزشی",
    "executive": "معاون اجرایی",
    "cultural": "معاون پرورشی",
    "advisor": "مشاوره",
    "teacher": "دبیران",
    "student": "دانش‌آموز",
    "parent": "اولیا",
}

PANELS = [
    ("management", "مدیریت"),
    ("educational", "معاون آموزشی"),
    ("executive", "معاون اجرایی"),
    ("cultural", "معاون پرورشی"),
    ("advisor", "مشاوره"),
    ("teachers", "دبیران"),
    ("students", "دانش‌آموزان"),
    ("parents", "اولیا"),
    ("finance", "مالی"),
    ("payment", "پرداخت آنلاین"),
    ("online", "کلاس‌های آنلاین"),
    ("teacher_exams", "آزمون آنلاین"),
    ("smart_board", "تابلو هوشمند"),
    ("ai", "هوش مصنوعی"),
    ("reports", "گزارش‌ها"),
    ("schedule", "برنامه هفتگی"),
    ("messages", "صندوق پیام‌ها"),
    ("settings", "تنظیمات"),
    ("about", "درباره برنامه"),
]

# The table fields are copied from the mother project's CompleteTabs contract.
TABLES = {
    "students": ["id","first_name","last_name","national_code","student_code","grade","class_name","phone","parent_phone","email","address"],
    "teachers": ["id","first_name","last_name","national_code","phone","email","subject","grades"],
    "staff": ["id","first_name","last_name","role","phone","employee_code","national_code","employment_status"],
    "attendance": ["id","student_id","date","status","description"],
    "teacher_attendance": ["id","student_id","teacher_id","class_name","subject","attendance_date","status","description"],
    "grades": ["id","student_id","subject","exam_name","score","grade_type","term","grade_date"],
    "grade_items": ["id","student_id","teacher_id","subject","grade_type","term","score","grade_date","description"],
    "assignments": ["id","student_id","teacher","subject","title","due_date","status"],
    "educational_activities": ["id","student_id","teacher_id","subject","title","activity_date","description"],
    "teacher_exams": ["id","teacher_id","title","subject","grade","class_name","exam_type","exam_date","duration"],
    "lesson_plans": ["id","teacher_id","teacher_name","subject","grade","class_name","title","objective","content","session_date","created_at"],
    "teacher_meetings": ["id","teacher_id","student_id","student_name","parent_name","meeting_at","subject","status","report"],
    "executive_classes": ["id","name","grade","teacher","created_at"],
    "executive_operations": ["id","operation_type","title","student_id","class_name","status","operation_date","description"],
    "executive_reports": ["id","title","report_type","student_id","class_name","report_date","created_by"],
    "weekly_schedule": ["id","teacher","hours","grade","class_count","subject","bell_pattern","class_names"],
    "exam_schedule": ["id","subject","grade","exam_date","duration","weight"],
    "cultural_activity_registrations": ["id","student_id","activity_id","activity_title","activity_kind","fee","payment_status","registration_date"],
    "competitions": ["id","title","category","start_date","end_date","status"],
    "cultural_reports": ["id","title","report_type","activity_id","report_date"],
    "payment_records": ["id","student_id","parent_username","title","amount","status","payment_date"],
    "school_events": ["id","event_type","title","actor_username","created_at"],
    "smart_board_content": ["id","title","content","class_id","teacher_id","content_date_shamsi"],
    "smart_board_whiteboards": ["id","title","content","class_id","teacher_id","board_date"],
    "smart_board_files": ["id","title","file_path","file_type","class_id","teacher_id"],
    "smart_board_media": ["id","title","media_path","media_type","class_id","teacher_id"],
    "smart_board_quizzes": ["id","title","question","correct_option","class_id","teacher_id","quiz_date_shamsi"],
    "smart_board_activities": ["id","title","activity_text","class_id","teacher_id","activity_date_shamsi"],
    "ai_assistant_sessions": ["id","username","role","title","request_date_shamsi"],
    "ai_questions": ["id","username","role","question","answer","answer_date_shamsi"],
    "ai_educational_analysis": ["id","student_id","teacher_id","subject","period","score","risk_level","analysis_date_shamsi"],
    "ai_smart_reports": ["id","title","report_type","target_type","target_id","created_by","report_date_shamsi"],
    "parent_children": ["id","first_name","last_name","student_code","grade","class_name","parent_phone"],
    "discipline_records": ["id","student_id","problem_type","description","status","reported_by","created_at"],
    "online_classes": ["id","title","subject","lesson","teacher","grade","class_name","duration","start_time_shamsi","end_time_shamsi","status","join_url","meeting_url"],
    "online_attendance": ["id","student_id","class_id","check_number","status","checked_at","leave_time"],
    "quiz_questions": ["id","quiz_id","question_type","question","options_json","correct_answer","accepted_answers","points"],
    "school_profile": ["id","school_name","school_code","principal_name","academic_year","phone","address"],
    "payment_offers": ["id","title","amount","payment_reason","target_type","target_value","active"],
}

ROLE_MODULES = {
    "manager": [
        ("users","مدیریت کاربران و کارکنان","staff"),
        ("students","دانش‌آموزان","students"),
        ("teachers","دبیران","teachers"),
        ("classes","کلاس‌ها","executive_classes"),
        ("announcements","اطلاعیه‌ها","school_events"),
        ("reports","گزارش‌ها","executive_reports"),
        ("schedule","برنامه هفتگی","weekly_schedule"),
        ("exam_schedule","برنامه امتحانات","exam_schedule"),
        ("finance","امور مالی","payment_records"),
        ("messages","صندوق پیام‌ها","school_events"),
    ],
    "educational": [
        ("attendance","حضور و غیاب","attendance"),
        ("discipline","موارد انضباطی","discipline_records"),
        ("referrals","ارجاعات آموزشی","executive_operations"),
        ("meetings","جلسات اولیا","teacher_meetings"),
        ("online","کلاس‌های آنلاین","online_classes"),
        ("exams","آزمون‌ها","teacher_exams"),
        ("question_bank","بانک سؤال","quiz_questions"),
        ("notifications","اطلاع‌رسانی","school_events"),
        ("smart_board","تابلو هوشمند","smart_board_content"),
        ("reports","گزارش‌ها","executive_reports"),
    ],
    "executive": [
        ("students","دانش‌آموزان","students"),
        ("classes","کلاس‌ها","executive_classes"),
        ("operations","امور اجرایی","executive_operations"),
        ("reports","گزارش اجرایی","executive_reports"),
        ("schedule","برنامه هفتگی","weekly_schedule"),
        ("exam_schedule","امتحانات","exam_schedule"),
        ("attendance","حضور و غیاب","attendance"),
    ],
    "cultural": [
        ("activities","ثبت‌نام فعالیت‌ها","cultural_activity_registrations"),
        ("competitions","مسابقات","competitions"),
        ("reports","گزارش‌های پرورشی","cultural_reports"),
        ("messages","پیام‌ها و رویدادها","school_events"),
    ],
    "advisor": [
        ("students","دانش‌آموزان","students"),
        ("referrals","ارجاعات مشاوره","advisor_workspace"),
        ("meetings","جلسات","advisor_workspace"),
        ("smart_guidance","هدایت تحصیلی هوشمند","ai_educational_analysis"),
        ("discipline","موارد انضباطی","discipline_records"),
        ("messages","پیام‌ها","school_events"),
    ],
    "teacher": [
        ("attendance","حضور و غیاب کلاس","teacher_attendance"),
        ("grades","ثبت نمره","grade_items"),
        ("assignments","تکالیف","assignments"),
        ("lesson_plans","طرح درس","lesson_plans"),
        ("meetings","جلسات اولیا","teacher_meetings"),
        ("online","کلاس آنلاین","online_classes"),
        ("exams","آزمون آنلاین","teacher_exams"),
        ("question_bank","بانک سؤال","quiz_questions"),
        ("reports","گزارش عملکرد","teacher_exams"),
    ],
    "student": [
        ("profile","پرونده من","students"),
        ("grades","کارنامه و نمرات","grades"),
        ("attendance","حضور و غیاب","attendance"),
        ("assignments","تکالیف","assignments"),
        ("activities","فعالیت‌های آموزشی","educational_activities"),
        ("schedule","برنامه هفتگی","weekly_schedule"),
        ("exams","آزمون‌ها","teacher_exams"),
        ("messages","پیام‌ها و اطلاعیه‌ها","school_events"),
    ],
    "parent": [
        ("children","فرزندان","students"),
        ("grades","کارنامه و نمرات","grades"),
        ("attendance","حضور و غیاب","attendance"),
        ("assignments","تکالیف","assignments"),
        ("activities","فعالیت‌های آموزشی","educational_activities"),
        ("schedule","برنامه هفتگی","weekly_schedule"),
        ("exams","امتحانات","exam_schedule"),
        ("payments","پرداخت‌ها و امور مالی","payment_records"),
        ("cultural","فعالیت‌های فرهنگی","cultural_activity_registrations"),
        ("messages","پیام‌ها و اطلاعیه‌ها","school_events"),
    ],
}

PANEL_ROLES = {
    "management":"manager","educational":"educational","executive":"executive","cultural":"cultural",
    "advisor":"advisor","teachers":"teacher","students":"student","parents":"parent",
    "finance":"manager","payment":"parent","online":"teacher","teacher_exams":"teacher",
    "smart_board":"teacher","ai":"advisor","reports":"manager","schedule":"manager",
    "messages":"manager","settings":"manager","about":"manager",
}

PANEL_MODULES = {
    "finance":[("accounts","حساب‌های مالی","payment_records"),("payments","سوابق پرداخت","payment_records"),("reports","گزارش مالی","executive_reports")],
    "payment":[("payments","پرداخت‌ها","payment_records"),("offers","خدمات و مبالغ","payment_records")],
    "online":[("classes","کلاس‌های آنلاین","online_classes"),("attendance","کنترل حضور آنلاین","online_attendance"),("reports","گزارش کلاس آنلاین","online_attendance")],
    "teacher_exams":[("exams","آزمون‌ها","teacher_exams"),("questions","بانک سؤال","quiz_questions"),("shares","اشتراک آزمون","teacher_exams"),("schedule","زمان‌بندی آزمون","exam_schedule")],
    "smart_board":[("content","محتوای آموزشی","smart_board_content"),("whiteboards","تخته‌ها","smart_board_whiteboards"),("files","فایل‌ها","smart_board_files"),("media","رسانه‌ها","smart_board_media"),("quizzes","آزمونک‌ها","smart_board_quizzes"),("activities","فعالیت‌ها","smart_board_activities")],
    "ai":[("sessions","جلسات هوش مصنوعی","ai_assistant_sessions"),("questions","پرسش‌های هوشمند","ai_questions"),("analysis","تحلیل آموزشی","ai_educational_analysis"),("reports","گزارش هوشمند","ai_smart_reports"),("guidance","هدایت تحصیلی هوشمند","ai_educational_analysis")],
    "reports":[("executive","گزارش‌های اجرایی","executive_reports"),("activities","گزارش فعالیت‌ها","cultural_reports"),("analysis","تحلیل آموزشی","ai_educational_analysis")],
    "schedule":[("weekly","برنامه هفتگی","weekly_schedule"),("exams","برنامه امتحانات","exam_schedule")],
    "messages":[("announcements","اطلاعیه‌ها","school_events"),("messages","صندوق پیام‌ها","school_events")],
    "settings":[("profile","تنظیمات حساب","staff"),("school","اطلاعات مدرسه","school_profile")],
    "about":[("about","درباره فراهوش","school_profile")],
}
