-- Frahoosh: parent/student participation and school-controlled activity fees.
-- Run this migration in the same Supabase project used by the Android build.

create table if not exists public.activity_offers (
  id bigint generated by default as identity primary key,
  school_id text,
  activity_key text not null,
  title text not null,
  amount bigint not null default 0 check (amount >= 0),
  active boolean not null default true,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_offers_school_activity
  on public.activity_offers (school_id, activity_key, active);

create table if not exists public.activity_registrations (
  id bigint generated by default as identity primary key,
  school_id text,
  activity_key text not null,
  role text not null,
  national_code text,
  display_name text,
  selections jsonb not null default '[]'::jsonb,
  sport_mode text,
  team_name text,
  team_members jsonb not null default '[]'::jsonb,
  offer_id bigint references public.activity_offers(id) on delete set null,
  amount bigint not null default 0 check (amount >= 0),
  payment_status text not null default 'free',
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_registrations_user
  on public.activity_registrations (school_id, national_code, created_at desc);

alter table public.activity_offers enable row level security;
alter table public.activity_registrations enable row level security;

-- Authenticated users can see active offers. Management-side offer creation/editing
-- should be restricted further in the school's production policy/RPC according to its
-- existing role/profile model.
drop policy if exists activity_offers_read on public.activity_offers;
create policy activity_offers_read
  on public.activity_offers for select
  to authenticated
  using (active = true);

drop policy if exists activity_registrations_insert on public.activity_registrations;
create policy activity_registrations_insert
  on public.activity_registrations for insert
  to authenticated
  with check (true);

drop policy if exists activity_registrations_read on public.activity_registrations;
create policy activity_registrations_read
  on public.activity_registrations for select
  to authenticated
  using (true);

-- Starter offers are intentionally NOT inserted here. The school must decide whether
-- each activity is free or paid and set the amount itself.
