-- Frahoosh operational core: online classrooms + online exams.
-- Safe to run after the existing school schema. Every CREATE/ALTER is idempotent.

create table if not exists public.online_classes (
  id bigint generated by default as identity primary key,
  title text not null,
  subject text,
  lesson text,
  teacher text,
  grade text,
  class_name text,
  duration integer not null default 60,
  start_time_shamsi text,
  end_time_shamsi text,
  status text not null default 'inactive',
  join_url text,
  meeting_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_sessions (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_students (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  student_id bigint,
  student_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_teachers (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  teacher_id bigint,
  teacher_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_whiteboards (
  id bigint generated by default as identity primary key,
  class_id bigint,
  content text,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_exams (
  id bigint generated by default as identity primary key,
  teacher_id bigint,
  title text not null,
  subject text,
  grade text,
  class_name text,
  exam_type text default 'آزمون آنلاین',
  duration integer not null default 45,
  description text,
  published boolean not null default false,
  secure_mode boolean not null default true,
  standard_mode boolean not null default true,
  max_attempts integer not null default 1,
  passing_score numeric default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint references public.teacher_exams(id) on delete cascade,
  question text not null,
  option1 text,
  option2 text,
  option3 text,
  option4 text,
  correct_answer text,
  points numeric not null default 1,
  question_type text not null default 'multiple_choice',
  options_json jsonb not null default '[]'::jsonb,
  accepted_answers text,
  difficulty text,
  cognitive_level text,
  auto_grade boolean not null default true,
  negative_score numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_exam_slots (
  id bigint generated by default as identity primary key,
  quiz_id bigint references public.teacher_exams(id) on delete cascade,
  class_name text,
  exam_date_shamsi text,
  start_time_shamsi text,
  end_time_shamsi text,
  duration integer,
  coordinated boolean not null default false,
  secure_mode boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_exam_shares (
  id bigint generated by default as identity primary key,
  quiz_id bigint references public.teacher_exams(id) on delete cascade,
  share_code text unique not null,
  target_school_id text,
  target_class_name text,
  start_at timestamptz,
  end_at timestamptz,
  duration_minutes integer not null default 45,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_exam_attempts (
  id bigint generated by default as identity primary key,
  quiz_id bigint references public.teacher_exams(id) on delete cascade,
  student_id bigint,
  student_username text,
  started_at timestamptz,
  submitted_at timestamptz,
  status text not null default 'started',
  score numeric not null default 0,
  max_score numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_exam_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint references public.teacher_exam_attempts(id) on delete cascade,
  question_id bigint references public.quiz_questions(id) on delete cascade,
  answer text,
  auto_correct boolean,
  score numeric not null default 0,
  teacher_score numeric,
  created_at timestamptz not null default now()
);

create index if not exists idx_online_classes_status on public.online_classes(status);
create index if not exists idx_exam_questions_quiz on public.quiz_questions(quiz_id);
create index if not exists idx_exam_slots_quiz on public.teacher_exam_slots(quiz_id);
create index if not exists idx_exam_shares_code on public.teacher_exam_shares(share_code,active);
create index if not exists idx_exam_attempts_quiz_student on public.teacher_exam_attempts(quiz_id,student_id);

-- Ensure columns are present if an older version of these tables already exists.
alter table public.online_classes add column if not exists join_url text;
alter table public.online_classes add column if not exists meeting_url text;
alter table public.online_classes add column if not exists start_time_shamsi text;
alter table public.online_classes add column if not exists end_time_shamsi text;
alter table public.quiz_questions add column if not exists options_json jsonb not null default '[]'::jsonb;
alter table public.quiz_questions add column if not exists accepted_answers text;
alter table public.quiz_questions add column if not exists difficulty text;
alter table public.quiz_questions add column if not exists cognitive_level text;
alter table public.quiz_questions add column if not exists auto_grade boolean not null default true;
alter table public.quiz_questions add column if not exists negative_score numeric not null default 0;

-- RPC: create an exam share.
create or replace function public.create_teacher_exam_share(
  p_quiz_id bigint,
  p_target_school_id text default null,
  p_target_class_name text default null,
  p_start_at timestamptz default null,
  p_end_at timestamptz default null,
  p_duration_minutes integer default 45
) returns table(share_code text)
language plpgsql security definer set search_path=public
as $$
declare c text;
begin
  c := 'FRAH-' || upper(substr(md5(random()::text || clock_timestamp()::text),1,8));
  insert into public.teacher_exam_shares(quiz_id,share_code,target_school_id,target_class_name,start_at,end_at,duration_minutes,active)
  values(p_quiz_id,c,p_target_school_id,p_target_class_name,p_start_at,p_end_at,p_duration_minutes,true);
  return query select c;
end;
$$;

-- RPC: load an active shared exam. Question order/options are randomized on the client.
create or replace function public.get_shared_exam(p_share_code text)
returns jsonb
language plpgsql security definer set search_path=public
as $$
declare s public.teacher_exam_shares; q public.teacher_exams; result jsonb;
begin
  select * into s from public.teacher_exam_shares where share_code=p_share_code and active=true limit 1;
  if not found then return null; end if;
  if s.start_at is not null and now()<s.start_at then return null; end if;
  if s.end_at is not null and now()>s.end_at then return null; end if;
  select * into q from public.teacher_exams where id=s.quiz_id and published=true limit 1;
  if not found then return null; end if;
  result := to_jsonb(q); result := result || jsonb_build_object('share_code',s.share_code,'duration',coalesce(s.duration_minutes,q.duration)); return result;
end;
$$;

create or replace function public.start_shared_teacher_exam(p_share_code text,p_student_id bigint default null,p_student_username text default null)
returns table(attempt_id bigint,duration integer)
language plpgsql security definer set search_path=public
as $$
declare s public.teacher_exam_shares; q public.teacher_exams; a public.teacher_exam_attempts;
begin
  select * into s from public.teacher_exam_shares where share_code=p_share_code and active=true limit 1;
  if not found then raise exception 'آزمون پیدا نشد یا فعال نیست'; end if;
  select * into q from public.teacher_exams where id=s.quiz_id and published=true limit 1;
  if not found then raise exception 'آزمون منتشر نشده است'; end if;
  insert into public.teacher_exam_attempts(quiz_id,student_id,student_username,started_at,status)
  values(q.id,p_student_id,p_student_username,now(),'started') returning * into a;
  return query select a.id,coalesce(s.duration_minutes,q.duration);
end;
$$;

create or replace function public.get_shared_attempt_questions(p_attempt_id bigint)
returns setof public.quiz_questions
language sql security definer set search_path=public
as $$
  select q.* from public.quiz_questions q
  where q.quiz_id=(select quiz_id from public.teacher_exam_attempts where id=p_attempt_id)
  order by random();
$$;

create or replace function public.submit_teacher_exam(p_attempt_id bigint,p_answers jsonb)
returns jsonb
language plpgsql security definer set search_path=public
as $$
declare a public.teacher_exam_attempts; q record; item jsonb; answer text; ok boolean; total numeric:=0; score numeric:=0;
begin
  select * into a from public.teacher_exam_attempts where id=p_attempt_id for update;
  if not found then raise exception 'تلاش آزمون پیدا نشد'; end if;
  for q in select * from public.quiz_questions where quiz_id=a.quiz_id loop
    total := total + coalesce(q.points,1);
    item := coalesce((select x from jsonb_array_elements(p_answers) x where (x->>'question_id')::bigint=q.id limit 1),'{}'::jsonb);
    answer := coalesce(item->>'answer','');
    ok := false;
    if q.question_type <> 'essay' then
      ok := answer=coalesce(q.correct_answer,'') or (q.accepted_answers is not null and answer=any(string_to_array(q.accepted_answers,'|')));
      if ok then score := score + coalesce(q.points,1); end if;
    end if;
    insert into public.teacher_exam_answers(attempt_id,question_id,answer,auto_correct,score) values(a.id,q.id,answer,ok,case when ok then q.points else 0 end);
  end loop;
  update public.teacher_exam_attempts set submitted_at=now(),status='submitted',score=score,max_score=total where id=a.id;
  return jsonb_build_object('score',score,'max_score',total);
end;
$$;

-- Authenticated users may use the operational APIs. Production deployments should
-- tighten these policies with the school's role/profile model.

do $$ declare t text; begin
  foreach t in array array['online_classes','online_class_sessions','online_class_students','online_class_teachers','smart_board_whiteboards','teacher_exams','quiz_questions','teacher_exam_slots','teacher_exam_shares','teacher_exam_attempts','teacher_exam_answers'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('drop policy if exists frahoosh_authenticated_all on public.%I',t);
    execute format('create policy frahoosh_authenticated_all on public.%I for all to authenticated using (true) with check (true)',t);
  end loop;
end $$;

grant execute on function public.create_teacher_exam_share(bigint,text,text,timestamptz,timestamptz,integer) to authenticated;
grant execute on function public.get_shared_exam(text) to authenticated;
grant execute on function public.start_shared_teacher_exam(text,bigint,text) to authenticated;
grant execute on function public.get_shared_attempt_questions(bigint) to authenticated;
grant execute on function public.submit_teacher_exam(bigint,jsonb) to authenticated;
