-- Frahoosh: school operational fields and workflow tables.

alter table public.students
  add column if not exists father_name text,
  add column if not exists mother_name text,
  add column if not exists birth_certificate_place text,
  add column if not exists birth_place text,
  add column if not exists religion text,
  add column if not exists sect text,
  add column if not exists nationality text,
  add column if not exists student_phone text,
  add column if not exists father_phone text,
  add column if not exists mother_phone text;

alter table public.teachers
  add column if not exists father_name text,
  add column if not exists personnel_code text,
  add column if not exists birth_certificate_place text,
  add column if not exists birth_place text,
  add column if not exists nationality text,
  add column if not exists religion text,
  add column if not exists sect text,
  add column if not exists service_years integer default 0;

alter table public.staff
  add column if not exists father_name text,
  add column if not exists personnel_code text,
  add column if not exists birth_certificate_place text,
  add column if not exists birth_place text,
  add column if not exists nationality text,
  add column if not exists religion text,
  add column if not exists sect text,
  add column if not exists service_years integer default 0;

create table if not exists public.discipline_records (
 id bigint generated by default as identity primary key, school_id text, student_id bigint, teacher_id bigint,
 discipline_type text not null, record_date text, decision_type text, deduct_score numeric default 0,
 referral_to text, description text, created_at timestamptz not null default now()
);
create table if not exists public.educational_followups (
 id bigint generated by default as identity primary key, school_id text, student_id bigint,
 followup_date text, followup_items text, decision text, created_at timestamptz not null default now()
);
create table if not exists public.academic_followups (like public.educational_followups including defaults);
create table if not exists public.certificate_requests (
 id bigint generated by default as identity primary key, school_id text, student_id bigint, student_name text,
 destination text not null, request_date text, status text not null default 'در انتظار بررسی',
 executive_note text, created_at timestamptz not null default now()
);
create table if not exists public.parent_meeting_requests (
 id bigint generated by default as identity primary key, school_id text, student_id bigint, parent_id bigint,
 target_type text not null, target_person text, requested_date text, reason text,
 status text not null default 'در انتظار تایید', created_at timestamptz not null default now()
);
create table if not exists public.student_referrals (
 id bigint generated by default as identity primary key, school_id text, student_id bigint, teacher_id bigint,
 referral_to text not null, reason text, referral_date text, status text not null default 'در انتظار بررسی',
 created_at timestamptz not null default now()
);
create table if not exists public.khwarizmi_registrations (
 id bigint generated by default as identity primary key, school_id text, title text, category text, grade text,
 class_name text, student_id bigint, status text not null default 'در انتظار بررسی', created_at timestamptz not null default now()
);
create table if not exists public.assignment_submissions (
 id bigint generated by default as identity primary key, school_id text, assignment_id bigint, student_id bigint,
 file_url text, answer_text text, submitted_at timestamptz not null default now(),
 status text not null default 'ارسال شد'
);
create table if not exists public.class_seat_assignments (
 id bigint generated by default as identity primary key, school_id text, class_id bigint, student_id bigint,
 seat_number integer, academic_year text, created_at timestamptz not null default now()
);
create table if not exists public.exam_seat_assignments (
 id bigint generated by default as identity primary key, school_id text, exam_id bigint, student_id bigint,
 subject text, exam_date text, seat_number integer, created_at timestamptz not null default now()
);
create table if not exists public.monthly_report_cards (
 id bigint generated by default as identity primary key, school_id text, student_id bigint, month_name text,
 report_data jsonb not null default '{}'::jsonb, active boolean not null default false,
 created_at timestamptz not null default now()
);
create table if not exists public.parent_activities (
 id bigint generated by default as identity primary key, school_id text, title text not null, activity_type text,
 event_date text, active boolean not null default true, description text, created_at timestamptz not null default now()
);
create table if not exists public.program_activations (
 id bigint generated by default as identity primary key, school_id text, program_key text not null, title text not null,
 active boolean not null default false, settings jsonb not null default '{}'::jsonb, activated_by text,
 created_at timestamptz not null default now()
);
create table if not exists public.lesson_plan_entries (
 id bigint generated by default as identity primary key, school_id text, teacher_id bigint, subject text,
 weekly_sessions integer, session_no integer, teaching_amount text, teaching_date text, teaching_title text,
 activity_type text, created_at timestamptz not null default now()
);
create table if not exists public.teacher_parent_meetings (
 id bigint generated by default as identity primary key, school_id text, teacher_id bigint, student_id bigint, parent_id bigint,
 requested_date text, status text not null default 'در انتظار تایید معاون آموزشی',
 manager_status text not null default 'در انتظار تایید مدیر', reason text, created_at timestamptz not null default now()
);
create table if not exists public.morning_ceremony (
 id bigint generated by default as identity primary key, school_id text, ceremony_date text, title text, qari_name text,
 leader_name text, program jsonb not null default '[]'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.activity_programs (
 id bigint generated by default as identity primary key, school_id text, activity_key text not null, title text not null,
 category text, active boolean not null default false, amount bigint not null default 0,
 settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

do $$
declare t text;
begin
  foreach t in array array[
    'discipline_records','educational_followups','academic_followups','certificate_requests','parent_meeting_requests',
    'student_referrals','khwarizmi_registrations','assignment_submissions','class_seat_assignments','exam_seat_assignments',
    'monthly_report_cards','parent_activities','program_activations','lesson_plan_entries','teacher_parent_meetings',
    'morning_ceremony','activity_programs'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists frahoosh_authenticated_all on public.%I', t);
    execute format('create policy frahoosh_authenticated_all on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;
