-- Frahoosh professional school workflows: cultural, student, parent, certificate and seating operations.
-- Idempotent migration. These tables back the specialized menus already exposed in the Android client.

create table if not exists public.activity_offers (
  id bigint generated by default as identity primary key,
  title text not null,
  activity_type text,
  description text,
  fixed_amount numeric default 0,
  capacity integer,
  start_date_shamsi text,
  end_date_shamsi text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.activity_registrations (
  id bigint generated by default as identity primary key,
  activity_id bigint references public.activity_offers(id) on delete set null,
  student_id bigint,
  student_name text,
  participation_type text,
  competition_type text,
  team_name text,
  team_members text,
  payment_offer_id bigint,
  payment_status text not null default 'pending',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.student_council (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  grade text,
  class_name text,
  candidate_role text,
  statement text,
  registration_date_shamsi text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.basij_registration (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  grade text,
  class_name text,
  guardian_phone text,
  registration_date_shamsi text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.school_ally (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  grade text,
  class_name text,
  responsibility text,
  registration_date_shamsi text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.school_mayor (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  grade text,
  class_name text,
  responsibility text,
  statement text,
  registration_date_shamsi text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.cultural_competitions (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  description text,
  registration_start_shamsi text,
  registration_end_shamsi text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.art_competitions (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  description text,
  registration_start_shamsi text,
  registration_end_shamsi text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.sport_competitions (
  id bigint generated by default as identity primary key,
  title text not null,
  sport_type text,
  participation_type text,
  description text,
  registration_start_shamsi text,
  registration_end_shamsi text,
  fixed_amount numeric default 0,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.morning_leaders (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  grade text,
  class_name text,
  role text,
  date_shamsi text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.qari_registration (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  grade text,
  class_name text,
  recitation_type text,
  date_shamsi text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.morning_ceremony (
  id bigint generated by default as identity primary key,
  date_shamsi text not null,
  weekday text,
  presenter text,
  qari text,
  morning_leader text,
  program_title text,
  notes text,
  status text not null default 'planned',
  created_at timestamptz not null default now()
);

create table if not exists public.student_class_info (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  grade text,
  class_name text,
  school_year text,
  classroom_seat text,
  exam_seat text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.parent_meeting_requests (
  id bigint generated by default as identity primary key,
  parent_id bigint,
  parent_name text,
  student_id bigint,
  student_name text,
  target_role text,
  target_name text,
  requested_date_shamsi text,
  requested_time text,
  reason text,
  status text not null default 'pending',
  educational_approval text,
  manager_approval text,
  created_at timestamptz not null default now()
);

create table if not exists public.parent_activities (
  id bigint generated by default as identity primary key,
  parent_id bigint,
  parent_name text,
  student_id bigint,
  student_name text,
  activity_type text,
  title text,
  registration_date_shamsi text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.monthly_report_cards (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  grade text,
  class_name text,
  month text,
  academic_average numeric,
  attendance_summary text,
  teacher_note text,
  status text not null default 'draft',
  published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.certificate_requests (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  certificate_type text default 'گواهی اشتغال به تحصیل',
  destination text not null,
  request_date_shamsi text,
  reason text,
  status text not null default 'pending',
  executive_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.assignment_submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint,
  student_id bigint,
  student_name text,
  class_name text,
  submitted_at_shamsi text,
  attachment_url text,
  answer_text text,
  teacher_feedback text,
  score numeric,
  status text not null default 'submitted',
  created_at timestamptz not null default now()
);

create table if not exists public.class_seat_assignments (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  class_name text,
  school_year text,
  seat_number integer,
  assigned_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.exam_seat_assignments (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  subject text,
  exam_date_shamsi text,
  exam_session text,
  seat_number integer,
  assigned_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.student_referrals (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  class_name text,
  referral_target text,
  reason text,
  date_shamsi text,
  followup_note text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_parent_meetings (
  id bigint generated by default as identity primary key,
  teacher_id bigint,
  teacher_name text,
  parent_id bigint,
  parent_name text,
  student_id bigint,
  student_name text,
  requested_date_shamsi text,
  requested_time text,
  reason text,
  educational_approval text,
  manager_approval text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.educational_followups (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  class_name text,
  date_shamsi text,
  followup_item text,
  decision text,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.academic_followups (
  id bigint generated by default as identity primary key,
  student_id bigint,
  student_name text,
  class_name text,
  subject text,
  date_shamsi text,
  followup_item text,
  decision text,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_reg_student on public.activity_registrations(student_id);
create index if not exists idx_parent_meeting_student on public.parent_meeting_requests(student_id);
create index if not exists idx_certificate_student on public.certificate_requests(student_id);
create index if not exists idx_monthly_report_student on public.monthly_report_cards(student_id);
create index if not exists idx_assignment_submission_student on public.assignment_submissions(student_id);
create index if not exists idx_exam_seat_student_subject on public.exam_seat_assignments(student_id,subject);

do $$ declare t text; begin
  foreach t in array array[
    'activity_offers','activity_registrations','student_council','basij_registration',
    'school_ally','school_mayor','cultural_competitions','art_competitions',
    'sport_competitions','morning_leaders','qari_registration','morning_ceremony',
    'student_class_info','parent_meeting_requests','parent_activities','monthly_report_cards',
    'certificate_requests','assignment_submissions','class_seat_assignments','exam_seat_assignments',
    'student_referrals','teacher_parent_meetings','educational_followups','academic_followups'
  ] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('drop policy if exists frahoosh_authenticated_all on public.%I',t);
    execute format('create policy frahoosh_authenticated_all on public.%I for all to authenticated using (true) with check (true)',t);
  end loop;
end $$;
