create table if not exists public.finance_transaction_attachments (
  id bigint generated by default as identity primary key,
  transaction_id integer not null references public.finance_transactions(id) on delete cascade,
  file_path text not null,
  file_name text not null default '',
  mime_type text not null default 'application/octet-stream',
  created_by text not null default '',
  created_at timestamptz not null default now()
);
alter table public.finance_transaction_attachments enable row level security;

create table if not exists public.finance_year_end_reports (
  id bigint generated by default as identity primary key,
  fiscal_year text not null,
  period_start text not null default '',
  period_end text not null default '',
  total_debit numeric not null default 0,
  total_credit numeric not null default 0,
  net_balance numeric not null default 0,
  snapshot_json text not null default '{}',
  pdf_path text,
  excel_path text,
  created_by text not null default '',
  created_at timestamptz not null default now()
);
alter table public.finance_year_end_reports enable row level security;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('finance-documents','finance-documents',false,20971520,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict(id) do update set file_size_limit=20971520,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists finance_docs_insert on storage.objects;
create policy finance_docs_insert on storage.objects for insert to authenticated
with check(bucket_id='finance-documents' and private.frahoosh_is_staff());

drop policy if exists finance_docs_select on storage.objects;
create policy finance_docs_select on storage.objects for select to authenticated
using(bucket_id='finance-documents' and private.frahoosh_is_staff());

drop policy if exists finance_docs_delete on storage.objects;
create policy finance_docs_delete on storage.objects for delete to authenticated
using(bucket_id='finance-documents' and private.frahoosh_is_staff());

drop policy if exists finance_attachment_staff_select on public.finance_transaction_attachments;
create policy finance_attachment_staff_select on public.finance_transaction_attachments
for select to authenticated using(private.frahoosh_is_staff());

drop policy if exists finance_attachment_staff_write on public.finance_transaction_attachments;
create policy finance_attachment_staff_write on public.finance_transaction_attachments
for all to authenticated using(private.frahoosh_is_staff()) with check(private.frahoosh_is_staff());

drop policy if exists finance_year_end_staff_select on public.finance_year_end_reports;
create policy finance_year_end_staff_select on public.finance_year_end_reports
for select to authenticated using(private.frahoosh_is_staff());

drop policy if exists finance_year_end_staff_write on public.finance_year_end_reports;
create policy finance_year_end_staff_write on public.finance_year_end_reports
for all to authenticated using(private.frahoosh_is_staff()) with check(private.frahoosh_is_staff());

create index if not exists idx_finance_tx_attachment_tx on public.finance_transaction_attachments(transaction_id);
create index if not exists idx_finance_year_end_fiscal on public.finance_year_end_reports(fiscal_year);