-- Frahoosh operational readiness: identity confirmation, robust role resolution,
-- payment fields, and write policies for the real school workflows.
-- Idempotent: preserves existing data and policies.

-- 1) Identity confirmation is server-side and applies to every school member.
create table if not exists public.identity_confirmations (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  username text,
  role text not null default 'student',
  profile_table text,
  profile_id bigint,
  student_id bigint,
  confirmation_status text not null default 'confirmed',
  snapshot jsonb default '{}'::jsonb,
  note text,
  confirmed_at timestamptz not null default now()
);
alter table public.identity_confirmations add column if not exists profile_table text;
alter table public.identity_confirmations add column if not exists profile_id bigint;
alter table public.identity_confirmations add column if not exists snapshot jsonb default '{}'::jsonb;
alter table public.identity_confirmations alter column student_id drop not null;

create index if not exists idx_identity_confirmations_user
  on public.identity_confirmations(auth_user_id, confirmed_at desc);
create index if not exists idx_identity_confirmations_username
  on public.identity_confirmations(username, confirmed_at desc);

alter table public.identity_confirmations enable row level security;
drop policy if exists identity_confirmation_insert on public.identity_confirmations;
create policy identity_confirmation_insert on public.identity_confirmations
  for insert to authenticated with check (true);
drop policy if exists identity_confirmation_owner_read on public.identity_confirmations;
create policy identity_confirmation_owner_read on public.identity_confirmations
  for select to authenticated
  using (
    (auth_user_id is not null and auth_user_id = auth.uid())
    or lower(coalesce(username,'')) = lower(coalesce(auth.jwt()->>'email',''))
    or (select private.frahoosh_is_staff())
  );
drop policy if exists identity_confirmation_owner_update on public.identity_confirmations;
create policy identity_confirmation_owner_update on public.identity_confirmations
  for update to authenticated
  using (
    (auth_user_id is not null and auth_user_id = auth.uid())
    or lower(coalesce(username,'')) = lower(coalesce(auth.jwt()->>'email',''))
    or (select private.frahoosh_is_staff())
  )
  with check (
    (auth_user_id is not null and auth_user_id = auth.uid())
    or lower(coalesce(username,'')) = lower(coalesce(auth.jwt()->>'email',''))
    or (select private.frahoosh_is_staff())
  );

-- 2) Persist the one-time confirmation flag on the account profile.
alter table if exists public.account_settings
  add column if not exists identity_confirmed boolean not null default false,
  add column if not exists identity_confirmed_at timestamptz,
  add column if not exists identity_snapshot jsonb default '{}'::jsonb,
  add column if not exists linked_student_id bigint,
  add column if not exists linked_teacher_id bigint,
  add column if not exists linked_staff_id bigint,
  add column if not exists role text;

-- 3) The payment UI uses these fields; older installations only had title/amount/status.
alter table if exists public.payment_offers
  add column if not exists target_type text,
  add column if not exists target_value text,
  add column if not exists active boolean not null default true,
  add column if not exists manual_amount boolean not null default false,
  add column if not exists payment_reason text,
  add column if not exists gateway_enabled boolean not null default false,
  add column if not exists account_id bigint,
  add column if not exists card_number text,
  add column if not exists destination text;

alter table if exists public.payment_attempts
  add column if not exists payer_username text,
  add column if not exists payer_role text,
  add column if not exists student_id bigint,
  add column if not exists description text,
  add column if not exists gateway_ref text;

alter table if exists public.payment_records
  add column if not exists payment_type text,
  add column if not exists gateway text,
  add column if not exists description text;

-- 4) Make the authenticated identity helpers use the same identity sources as login.
create or replace function private.frahoosh_current_role()
returns text language sql stable security definer set search_path=''
as $$
  select coalesce(
    (
      select nullif(trim(coalesce(u.role, a.role, (p.u_permissions->>'role'))),'')
      from public.users u
      full join public.account_settings a
        on lower(coalesce(a.email,'')) = lower(coalesce(auth.jwt()->>'email',''))
        or lower(coalesce(a.username,'')) = lower(coalesce(auth.jwt()->>'email',''))
      cross join lateral (
        select case when jsonb_typeof(coalesce(u.permissions,'{}'::jsonb))='object'
                    then coalesce(u.permissions,'{}'::jsonb) else '{}'::jsonb end as u_permissions
      ) p
      where lower(coalesce(u.username,'')) = lower(coalesce(auth.jwt()->>'email',''))
         or lower(coalesce(u.username,'')) = lower(coalesce(a.username,''))
         or lower(coalesce(a.email,'')) = lower(coalesce(auth.jwt()->>'email',''))
         or (
           nullif(trim(coalesce(a.national_code,'')),'') is not null
           and lower(trim(coalesce(u.username,''))) = lower(trim(coalesce(a.national_code,'')))
         )
      order by case
        when lower(coalesce(u.username,'')) = lower(coalesce(auth.jwt()->>'email','')) then 0
        when lower(coalesce(a.email,'')) = lower(coalesce(auth.jwt()->>'email','')) then 1
        else 2
      end
      limit 1
    ),
    ''
  )
$$;

create or replace function private.frahoosh_current_student_id()
returns bigint language sql stable security definer set search_path=''
as $$
  select coalesce(
    (
      select coalesce(u.linked_student_id,a.linked_student_id)
      from public.users u
      full join public.account_settings a
        on lower(coalesce(a.email,'')) = lower(coalesce(auth.jwt()->>'email',''))
        or lower(coalesce(a.username,'')) = lower(coalesce(auth.jwt()->>'email',''))
      where lower(coalesce(u.username,'')) = lower(coalesce(auth.jwt()->>'email',''))
         or lower(coalesce(a.email,'')) = lower(coalesce(auth.jwt()->>'email',''))
         or lower(coalesce(a.username,'')) = lower(coalesce(auth.jwt()->>'email',''))
         or lower(coalesce(u.username,'')) = lower(coalesce(a.national_code,''))
      limit 1
    ),
    (
      select s.id
      from public.students s
      join public.account_settings a on s.national_code=a.national_code
      where lower(coalesce(a.email,''))=lower(coalesce(auth.jwt()->>'email',''))
         or lower(coalesce(a.username,''))=lower(coalesce(auth.jwt()->>'email',''))
      limit 1
    )
  )
$$;

create or replace function private.frahoosh_current_teacher_id()
returns bigint language sql stable security definer set search_path=''
as $$
  select coalesce(
    (
      select coalesce(u.linked_teacher_id,a.linked_teacher_id)
      from public.users u
      full join public.account_settings a
        on lower(coalesce(a.email,'')) = lower(coalesce(auth.jwt()->>'email',''))
        or lower(coalesce(a.username,'')) = lower(coalesce(auth.jwt()->>'email',''))
      where lower(coalesce(u.username,'')) = lower(coalesce(auth.jwt()->>'email',''))
         or lower(coalesce(a.email,'')) = lower(coalesce(auth.jwt()->>'email',''))
         or lower(coalesce(a.username,'')) = lower(coalesce(auth.jwt()->>'email',''))
         or lower(coalesce(u.username,'')) = lower(coalesce(a.national_code,''))
      limit 1
    ),
    (
      select t.id
      from public.teachers t
      join public.account_settings a on t.national_code=a.national_code
      where lower(coalesce(a.email,''))=lower(coalesce(auth.jwt()->>'email',''))
         or lower(coalesce(a.username,''))=lower(coalesce(auth.jwt()->>'email',''))
      limit 1
    )
  )
$$;

create or replace function private.frahoosh_is_staff()
returns boolean language sql stable security definer set search_path=''
as $$
  select lower(coalesce(private.frahoosh_current_role(),''))
    = any(array[
      'مدیر','مدیریت','manager',
      'معاون آموزشی','educational',
      'معاون اجرایی','اجرایی','executive',
      'معاون پرورشی','cultural',
      'مشاوره','مشاور','counselor','advisor',
      'دبیر','معلم','teacher'
    ])
$$;

-- 5) Ensure the real CRUD tables allow the roles that the Android contract exposes.
-- Manager has full operational access. Educational/executive/cultural/advisor staff
-- can operate the records assigned to their panels; teacher can write teacher-owned data.
do $$
declare t text;
begin
  foreach t in array array[
    'students','teachers','staff','teacher_classes','attendance','grades','student_grades',
    'assignments','discipline_records','educational_followups','academic_followups',
    'teacher_exams','quiz_questions','online_classes','messages','message_targets',
    'message_reads','meeting_requests','school_events','school_class_config',
    'report_cards','weekly_schedule','exam_schedule','finance_accounts',
    'finance_transactions','finance_donations','payment_offers','payment_attempts',
    'payment_records','payment_transactions','certificate_requests','archive_items',
    'assets','student_cards','class_cards','class_seat_assignments','exam_seat_assignments'
  ] loop
    if to_regclass('public.'||t) is not null then
      execute format('drop policy if exists frahoosh_manager_operational_write on public.%I',t);
      execute format(
        'create policy frahoosh_manager_operational_write on public.%I for all to authenticated
         using ((select private.frahoosh_current_role()) = any(array[''manager'',''admin'',''مدیر'',''مدیریت'']))
         with check ((select private.frahoosh_current_role()) = any(array[''manager'',''admin'',''مدیر'',''مدیریت'']))',t);
    end if;
  end loop;
end $$;

-- Teacher-owned writes for the common teaching tables. Existing manager policy is
-- unaffected; these policies make teacher registration work even when linked ids
-- are populated only in account_settings.
drop policy if exists frahoosh_teacher_grades_insert on public.grades;
create policy frahoosh_teacher_grades_insert on public.grades
  for insert to authenticated
  with check (teacher_id=(select private.frahoosh_current_teacher_id()));
drop policy if exists frahoosh_teacher_grades_update on public.grades;
create policy frahoosh_teacher_grades_update on public.grades
  for update to authenticated
  using (teacher_id=(select private.frahoosh_current_teacher_id()))
  with check (teacher_id=(select private.frahoosh_current_teacher_id()));

drop policy if exists frahoosh_teacher_attendance_insert on public.attendance;
create policy frahoosh_teacher_attendance_insert on public.attendance
  for insert to authenticated
  with check (teacher_id=(select private.frahoosh_current_teacher_id()));
drop policy if exists frahoosh_teacher_attendance_update on public.attendance;
create policy frahoosh_teacher_attendance_update on public.attendance
  for update to authenticated
  using (teacher_id=(select private.frahoosh_current_teacher_id()))
  with check (teacher_id=(select private.frahoosh_current_teacher_id()));

drop policy if exists frahoosh_teacher_student_grades_insert on public.student_grades;
create policy frahoosh_teacher_student_grades_insert on public.student_grades
  for insert to authenticated
  with check (teacher_id=(select private.frahoosh_current_teacher_id()));
drop policy if exists frahoosh_teacher_student_grades_update on public.student_grades;
create policy frahoosh_teacher_student_grades_update on public.student_grades
  for update to authenticated
  using (teacher_id=(select private.frahoosh_current_teacher_id()))
  with check (teacher_id=(select private.frahoosh_current_teacher_id()));

grant select, insert, update, delete on table public.identity_confirmations to authenticated;
grant select, insert, update, delete on table public.account_settings to authenticated;
