-- Frahoosh ZIP canonical remaining module tables.
-- Completes the real Supabase backing tables for modules referenced by the
-- canonical ZIP/module catalog but not present in the original migrations.
-- Idempotent and safe to apply after the existing ZIP canonical migrations.

create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  title text,
  category text,
  quantity numeric default 0,
  location text,
  archived boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  student_id bigint,
  title text,
  code text,
  created_at timestamptz not null default now()
);

create table if not exists public.student_cards (
  id bigint generated by default as identity primary key,
  student_id bigint,
  card_type text,
  code text,
  created_at timestamptz not null default now()
);

create table if not exists public.class_cards (
  id bigint generated by default as identity primary key,
  student_id bigint,
  class_name text,
  code text,
  created_at timestamptz not null default now()
);

-- The ZIP already defines surveys; this keeps the Web/Android module contract
-- usable on Supabase installations that do not yet have the table.
create table if not exists public.executive_requests (
  id bigint generated by default as identity primary key,
  title text,
  requester text,
  status text,
  description text,
  role text,
  created_at timestamptz not null default now()
);

create table if not exists public.lesson_plans (
  id bigint generated by default as identity primary key,
  teacher_id bigint,
  teacher_name text,
  subject text,
  grade text,
  class_name text,
  title text,
  content text,
  session_date text,
  lesson_title text,
  description text,
  plan_date text,
  created_at timestamptz not null default now()
);

create table if not exists public.surveys (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  status text,
  audience text,
  start_at text,
  end_at text,
  created_by text,
  created_at timestamptz not null default now()
);

do $$
declare t text;
begin
  foreach t in array array[
    'assets','certificates','student_cards','class_cards','surveys','executive_requests','lesson_plans'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists frahoosh_zip_remaining_authenticated on public.%I', t);
    execute format(
      'create policy frahoosh_zip_remaining_authenticated on public.%I for all to authenticated using (true) with check (true)',
      t
    );
  end loop;
end $$;
