-- Frahoosh: parent/teacher/staff/counselor meeting workflow
-- Safe to run once in Supabase SQL Editor or as a migration.
create table if not exists public.meeting_requests (
  id bigint generated by default as identity primary key,
  school_id text,
  requester_user_id uuid,
  requester_role text not null,
  requester_name text not null,
  student_id bigint,
  parent_id bigint,
  target_user_id uuid,
  target_record_id bigint,
  target_role text not null,
  target_name text not null,
  meeting_date text not null,
  meeting_time text not null,
  meeting_period text,
  reason text not null,
  description text,
  status text not null default 'pending_manager'
    check (status in (
      'pending_manager',
      'rejected_by_manager',
      'referred_to_educational_deputy',
      'confirmed',
      'cancelled'
    )),
  manager_approved boolean not null default false,
  manager_approved_at timestamptz,
  manager_note text,
  referred_to_educational_deputy boolean not null default false,
  final_confirmed_date text,
  final_confirmed_time text,
  final_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_meeting_requests_requester
  on public.meeting_requests(requester_user_id, created_at desc);
create index if not exists idx_meeting_requests_target
  on public.meeting_requests(target_user_id, created_at desc);
create index if not exists idx_meeting_requests_status
  on public.meeting_requests(status, created_at desc);

alter table public.meeting_requests enable row level security;

drop policy if exists meeting_requests_insert_own on public.meeting_requests;
create policy meeting_requests_insert_own
on public.meeting_requests
for insert to authenticated
with check (requester_user_id = auth.uid());

drop policy if exists meeting_requests_select_own on public.meeting_requests;
create policy meeting_requests_select_own
on public.meeting_requests
for select to authenticated
using (
  requester_user_id = auth.uid()
  or target_user_id = auth.uid()
  or (auth.jwt() -> 'user_metadata' ->> 'role') in (
    'manager','admin','administrator','educational','معاون آموزشی','مدیر','مدیریت'
  )
);

drop policy if exists meeting_requests_update_management on public.meeting_requests;
create policy meeting_requests_update_management
on public.meeting_requests
for update to authenticated
using (
  (auth.jwt() -> 'user_metadata' ->> 'role') in (
    'manager','admin','administrator','مدیر','مدیریت'
  )
  or (
    status = 'referred_to_educational_deputy'
    and (auth.jwt() -> 'user_metadata' ->> 'role') in (
      'educational','معاون آموزشی'
    )
  )
)
with check (
  (auth.jwt() -> 'user_metadata' ->> 'role') in (
    'manager','admin','administrator','educational','معاون آموزشی','مدیر','مدیریت'
  )
);

-- Keep updated_at current without assuming an existing trigger/function.
create or replace function public.frahoosh_set_meeting_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_meeting_requests_updated_at on public.meeting_requests;
create trigger trg_meeting_requests_updated_at
before update on public.meeting_requests
for each row execute function public.frahoosh_set_meeting_updated_at();
