-- Frahoosh: complete missing workflow tables and relationship indexes
-- Re-runnable: production was updated first; this file keeps the schema reproducible.

create table if not exists public.meeting_requests (
  id bigint generated by default as identity primary key,
  title text, requester_username text, requester_name text, requester_role text,
  target_username text, target_name text, target_role text,
  student_id integer references public.students(id) on delete set null,
  teacher_id integer references public.teachers(id) on delete set null,
  parent_id text, parent_phone text, requested_day text, requested_date text,
  requested_time text, reason text, description text,
  status text not null default 'pending_manager',
  manager_status text not null default 'pending', educational_status text,
  manager_note text, educational_note text, final_date text, final_time text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.parent_meeting_requests (
  id bigint generated by default as identity primary key,
  parent_id text, parent_name text, parent_username text,
  student_id integer references public.students(id) on delete cascade, student_name text,
  target_role text, target_name text, requested_date_shamsi text, requested_time text,
  reason text, status text not null default 'pending', educational_approval text,
  manager_approval text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.teacher_meetings (
  id bigint generated by default as identity primary key,
  teacher_id bigint references public.teachers(id) on delete set null, teacher_name text,
  student_id bigint references public.students(id) on delete set null, student_name text,
  parent_name text, meeting_at text, subject text, status text not null default 'pending',
  report text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.transport_requests (
  id bigint generated by default as identity primary key,
  parent_username text, student_id bigint references public.students(id) on delete set null,
  address text, vehicle_type text, origin text, destination text, note text,
  status text not null default 'pending', created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_programs (
  id bigint generated by default as identity primary key, activity_key text, title text not null,
  category text, active boolean not null default true, amount integer, settings jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.counseling_classes (
  id bigint generated by default as identity primary key, title text not null, grade text,
  subject text, teacher_id bigint references public.teachers(id) on delete set null,
  active boolean not null default true, created_at timestamptz not null default now()
);

create table if not exists public.counseling_guidance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  grade text, interest text, aptitude text, recommendation text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.counselor_board (
  id bigint generated by default as identity primary key, title text not null, body text,
  active boolean not null default true, created_by text, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.meeting_requests enable row level security;
alter table public.parent_meeting_requests enable row level security;
alter table public.teacher_meetings enable row level security;
alter table public.transport_requests enable row level security;
alter table public.activity_programs enable row level security;
alter table public.counseling_classes enable row level security;
alter table public.counseling_guidance enable row level security;
alter table public.counselor_board enable row level security;

revoke all on table public.meeting_requests, public.parent_meeting_requests, public.teacher_meetings, public.transport_requests,
  public.activity_programs, public.counseling_classes, public.counseling_guidance, public.counselor_board from anon;
grant select, insert, update, delete on table public.meeting_requests, public.parent_meeting_requests, public.teacher_meetings,
  public.transport_requests, public.activity_programs, public.counseling_classes, public.counseling_guidance, public.counselor_board to authenticated;
grant usage, select on sequence public.meeting_requests_id_seq, public.parent_meeting_requests_id_seq,
  public.teacher_meetings_id_seq, public.transport_requests_id_seq, public.activity_programs_id_seq,
  public.counseling_classes_id_seq, public.counseling_guidance_id_seq, public.counselor_board_id_seq to authenticated;

drop policy if exists "meeting_requests_staff_all" on public.meeting_requests;
drop policy if exists "meeting_requests_owner_read" on public.meeting_requests;
drop policy if exists "meeting_requests_parent_write" on public.meeting_requests;
create policy "meeting_requests_staff_all" on public.meeting_requests for all to authenticated
using ((select private.frahoosh_is_staff())) with check ((select private.frahoosh_is_staff()));
create policy "meeting_requests_owner_read" on public.meeting_requests for select to authenticated
using (
  lower(coalesce(requester_username,'')) = lower(coalesce((select email from auth.users where id=(select auth.uid())),'')) or
  student_id = (select private.frahoosh_current_student_id()) or
  teacher_id = (select private.frahoosh_current_teacher_id())
);
create policy "meeting_requests_parent_write" on public.meeting_requests for all to authenticated
using (
  requester_role in ('parent','parents','ولی','اولیا')
  and lower(coalesce(requester_username,'')) =
      lower(coalesce((select national_code from public.account_settings where auth_user_id=(select auth.uid()) limit 1),''))
)
with check (
  requester_role in ('parent','parents','ولی','اولیا')
  and lower(coalesce(requester_username,'')) =
      lower(coalesce((select national_code from public.account_settings where auth_user_id=(select auth.uid()) limit 1),''))
);

drop policy if exists "parent_meeting_requests_staff_all" on public.parent_meeting_requests;
drop policy if exists "parent_meeting_requests_parent_all" on public.parent_meeting_requests;
create policy "parent_meeting_requests_staff_all" on public.parent_meeting_requests for all to authenticated
using ((select private.frahoosh_is_staff())) with check ((select private.frahoosh_is_staff()));
create policy "parent_meeting_requests_parent_all" on public.parent_meeting_requests for all to authenticated
using (lower(coalesce(parent_username,'')) = lower(coalesce((select national_code from public.account_settings where auth_user_id=(select auth.uid()) limit 1),''))
) with check (lower(coalesce(parent_username,'')) = lower(coalesce((select national_code from public.account_settings where auth_user_id=(select auth.uid()) limit 1),''))
);

drop policy if exists "teacher_meetings_staff_all" on public.teacher_meetings;
drop policy if exists "teacher_meetings_teacher_all" on public.teacher_meetings;
drop policy if exists "teacher_meetings_parent_read" on public.teacher_meetings;
create policy "teacher_meetings_staff_all" on public.teacher_meetings for all to authenticated
using ((select private.frahoosh_is_staff())) with check ((select private.frahoosh_is_staff()));
create policy "teacher_meetings_teacher_all" on public.teacher_meetings for all to authenticated
using (teacher_id=(select private.frahoosh_current_teacher_id()))
with check (teacher_id=(select private.frahoosh_current_teacher_id()));
create policy "teacher_meetings_parent_read" on public.teacher_meetings for select to authenticated
using (exists (
  select 1 from public.parent_children pc
  join public.account_settings a on lower(a.username)=lower(pc.parent_username)
  where pc.student_id=teacher_meetings.student_id and a.auth_user_id=(select auth.uid())
));

drop policy if exists "transport_requests_staff_all" on public.transport_requests;
drop policy if exists "transport_requests_parent_all" on public.transport_requests;
create policy "transport_requests_staff_all" on public.transport_requests for all to authenticated
using ((select private.frahoosh_is_staff())) with check ((select private.frahoosh_is_staff()));
create policy "transport_requests_parent_all" on public.transport_requests for all to authenticated
using (lower(coalesce(parent_username,'')) = lower(coalesce((select national_code from public.account_settings where auth_user_id=(select auth.uid()) limit 1),''))
) with check (lower(coalesce(parent_username,'')) = lower(coalesce((select national_code from public.account_settings where auth_user_id=(select auth.uid()) limit 1),''))
);

drop policy if exists "activity_programs_staff_all" on public.activity_programs;
drop policy if exists "activity_programs_authenticated_read" on public.activity_programs;
create policy "activity_programs_staff_all" on public.activity_programs for all to authenticated
using ((select private.frahoosh_is_staff())) with check ((select private.frahoosh_is_staff()));
create policy "activity_programs_authenticated_read" on public.activity_programs for select to authenticated using (active=true);

drop policy if exists "counseling_classes_staff_all" on public.counseling_classes;
drop policy if exists "counseling_classes_authenticated_read" on public.counseling_classes;
create policy "counseling_classes_staff_all" on public.counseling_classes for all to authenticated
using ((select private.frahoosh_is_staff())) with check ((select private.frahoosh_is_staff()));
create policy "counseling_classes_authenticated_read" on public.counseling_classes for select to authenticated using (active=true);

drop policy if exists "counseling_guidance_staff_all" on public.counseling_guidance;
drop policy if exists "counseling_guidance_student_read" on public.counseling_guidance;
drop policy if exists "counseling_guidance_parent_read" on public.counseling_guidance;
create policy "counseling_guidance_staff_all" on public.counseling_guidance for all to authenticated
using ((select private.frahoosh_is_staff())) with check ((select private.frahoosh_is_staff()));
create policy "counseling_guidance_student_read" on public.counseling_guidance for select to authenticated
using (student_id=(select private.frahoosh_current_student_id()));
create policy "counseling_guidance_parent_read" on public.counseling_guidance for select to authenticated
using (exists (
  select 1 from public.parent_children pc
  join public.account_settings a on lower(a.username)=lower(pc.parent_username)
  where pc.student_id=counseling_guidance.student_id and a.auth_user_id=(select auth.uid())
));

drop policy if exists "counselor_board_staff_all" on public.counselor_board;
drop policy if exists "counselor_board_authenticated_read" on public.counselor_board;
create policy "counselor_board_staff_all" on public.counselor_board for all to authenticated
using ((select private.frahoosh_is_staff())) with check ((select private.frahoosh_is_staff()));
create policy "counselor_board_authenticated_read" on public.counselor_board for select to authenticated using (active=true);

create index if not exists meeting_requests_student_id_idx on public.meeting_requests(student_id);
create index if not exists meeting_requests_teacher_id_idx on public.meeting_requests(teacher_id);
create index if not exists meeting_requests_requester_username_idx on public.meeting_requests(lower(requester_username));
create index if not exists parent_meeting_requests_student_id_idx on public.parent_meeting_requests(student_id);
create index if not exists teacher_meetings_teacher_id_idx on public.teacher_meetings(teacher_id);
create index if not exists teacher_meetings_student_id_idx on public.teacher_meetings(student_id);
create index if not exists transport_requests_student_id_idx on public.transport_requests(student_id);
create index if not exists transport_requests_parent_username_idx on public.transport_requests(lower(parent_username));
create index if not exists counseling_guidance_student_id_idx on public.counseling_guidance(student_id);

create index if not exists assignment_submissions_assignment_id_idx on public.assignment_submissions(assignment_id);
create index if not exists assignment_submissions_student_id_idx on public.assignment_submissions(student_id);
create index if not exists assignments_student_id_idx on public.assignments(student_id);
create index if not exists assignments_teacher_id_idx on public.assignments(teacher_id);
create index if not exists attendance_student_id_idx on public.attendance(student_id);
create index if not exists attendance_teacher_id_idx on public.attendance(teacher_id);
create index if not exists counseling_classes_teacher_id_idx on public.counseling_classes(teacher_id);
create index if not exists grades_student_id_idx on public.grades(student_id);
create index if not exists grades_teacher_id_idx on public.grades(teacher_id);
create index if not exists online_attendance_class_id_idx on public.online_attendance(class_id);
create index if not exists online_attendance_student_id_idx on public.online_attendance(student_id);
create index if not exists online_class_sessions_class_id_idx on public.online_class_sessions(class_id);
create index if not exists online_class_students_class_id_idx on public.online_class_students(class_id);
create index if not exists online_class_students_student_id_idx on public.online_class_students(student_id);
create index if not exists online_class_teachers_class_id_idx on public.online_class_teachers(class_id);
create index if not exists online_class_teachers_teacher_id_idx on public.online_class_teachers(teacher_id);
create index if not exists parent_meetings_student_id_idx on public.parent_meetings(student_id);
create index if not exists parent_meetings_teacher_id_idx on public.parent_meetings(teacher_id);
create index if not exists payment_attempts_offer_id_idx on public.payment_attempts(offer_id);
create index if not exists payment_attempts_student_id_idx on public.payment_attempts(student_id);
create index if not exists payment_records_student_id_idx on public.payment_records(student_id);
create index if not exists payment_transactions_student_id_idx on public.payment_transactions(student_id);
create index if not exists quiz_questions_quiz_id_idx on public.quiz_questions(quiz_id);
create index if not exists student_grades_student_id_idx on public.student_grades(student_id);
create index if not exists student_grades_teacher_id_idx on public.student_grades(teacher_id);
create index if not exists teacher_classes_teacher_id_idx on public.teacher_classes(teacher_id);
create index if not exists teacher_exam_answers_attempt_id_idx on public.teacher_exam_answers(attempt_id);
create index if not exists teacher_exam_shares_quiz_id_idx on public.teacher_exam_shares(quiz_id);
create index if not exists teacher_exams_teacher_id_idx on public.teacher_exams(teacher_id);
create index if not exists teacher_meetings_student_id_idx on public.teacher_meetings(student_id);
create index if not exists teacher_meetings_teacher_id_idx on public.teacher_meetings(teacher_id);
create index if not exists transport_requests_student_id_idx on public.transport_requests(student_id);
