-- School-wide directed relationship graph for real message routing.
create table if not exists public.school_relationships (
  id bigint generated by default as identity primary key,
  source_username text not null,
  source_role text not null,
  target_username text not null,
  target_role text not null,
  relation_type text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint school_relationships_unique unique (source_username, target_username, relation_type)
);

create index if not exists school_relationships_source_idx
  on public.school_relationships(source_username, active);
create index if not exists school_relationships_target_idx
  on public.school_relationships(target_username, active);

create or replace function public.sync_school_relationships_for_user()
returns trigger
language plpgsql
as $$
declare u record; src text := lower(coalesce(new.role,'')); tgt text;
begin
  for u in select username, role from public.users where username is not null and username <> new.username loop
    tgt := lower(coalesce(u.role,''));
    if (src in ('manager','admin','administrator','management')
      or src='student'
      or (src='parent' and tgt in ('teacher','manager','admin','administrator','management','educational','executive','cultural','advisor','counselor'))
      or (src='teacher' and tgt in ('student','parent','educational','executive','cultural','advisor','counselor','manager','admin','administrator','management'))
      or (src in ('advisor','counselor') and tgt in ('teacher','parent','student','educational','executive','cultural','manager','admin','administrator','management'))
      or (src='educational' and tgt in ('teacher','parent','student','advisor','counselor','manager','admin','administrator','management'))
      or (src='executive' and tgt in ('teacher','parent','student','advisor','counselor','manager','admin','administrator','management'))
      or (src='cultural' and tgt in ('teacher','parent','student','advisor','counselor','manager','admin','administrator','management'))) then
      insert into public.school_relationships(source_username,source_role,target_username,target_role,relation_type)
      values(new.username,src,u.username,tgt,case when src='student' and tgt='parent' then 'student_parent' else 'school_role' end)
      on conflict (source_username,target_username,relation_type) do update
      set source_role=excluded.source_role,target_role=excluded.target_role,active=true,updated_at=now();
    end if;
    if (tgt in ('manager','admin','administrator','management')
      or tgt='student'
      or (tgt='parent' and src in ('teacher','advisor','counselor','educational','executive','cultural'))
      or (tgt='teacher' and src in ('student','parent','advisor','counselor','educational','executive','cultural','manager','admin','administrator','management'))
      or (tgt in ('advisor','counselor') and src in ('teacher','parent','student','educational','executive','cultural','manager','admin','administrator','management'))
      or (tgt in ('educational','executive','cultural') and src in ('teacher','parent','student','advisor','counselor','manager','admin','administrator','management'))) then
      insert into public.school_relationships(source_username,source_role,target_username,target_role,relation_type)
      values(u.username,tgt,new.username,src,case when tgt='student' and src='parent' then 'student_parent' else 'school_role' end)
      on conflict (source_username,target_username,relation_type) do update
      set source_role=excluded.source_role,target_role=excluded.target_role,active=true,updated_at=now();
    end if;
  end loop;
  return new;
end;
$$;

drop trigger if exists trg_sync_school_relationships_user on public.users;
create trigger trg_sync_school_relationships_user
after insert or update of username, role on public.users
for each row execute function public.sync_school_relationships_for_user();

create or replace function public.sync_parent_student_relationship()
returns trigger
language plpgsql
as $$
declare student_username text;
begin
  select username into student_username from public.users where linked_student_id = new.student_id limit 1;
  if student_username is not null and new.parent_username is not null then
    insert into public.school_relationships(source_username,source_role,target_username,target_role,relation_type)
    values(new.parent_username,'parent',student_username,'student','parent_student')
    on conflict (source_username,target_username,relation_type) do update set active=true,updated_at=now();
    insert into public.school_relationships(source_username,source_role,target_username,target_role,relation_type)
    values(student_username,'student',new.parent_username,'parent','student_parent')
    on conflict (source_username,target_username,relation_type) do update set active=true,updated_at=now();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_sync_parent_student_relationship on public.parent_children;
create trigger trg_sync_parent_student_relationship
after insert or update of parent_username, student_id on public.parent_children
for each row execute function public.sync_parent_student_relationship();

insert into public.school_relationships(source_username,source_role,target_username,target_role,relation_type)
select s.username,lower(s.role),t.username,lower(t.role),
case when lower(s.role)='student' and lower(t.role)='parent' then 'student_parent' else 'school_role' end
from public.users s cross join public.users t
where s.username is not null and t.username is not null and s.username<>t.username
and (lower(s.role) in ('manager','admin','administrator','management') or lower(s.role)='student'
or (lower(s.role)='parent' and lower(t.role) in ('teacher','manager','admin','administrator','management','educational','executive','cultural','advisor','counselor'))
or (lower(s.role)='teacher' and lower(t.role) in ('student','parent','educational','executive','cultural','advisor','counselor','manager','admin','administrator','management'))
or (lower(s.role) in ('advisor','counselor') and lower(t.role) in ('teacher','parent','student','educational','executive','cultural','manager','admin','administrator','management'))
or (lower(s.role) in ('educational','executive','cultural') and lower(t.role) in ('teacher','parent','student','advisor','counselor','manager','admin','administrator','management')))
on conflict (source_username,target_username,relation_type) do update set active=true,updated_at=now();

insert into public.school_relationships(source_username,source_role,target_username,target_role,relation_type)
select pc.parent_username,'parent',u.username,'student','parent_student'
from public.parent_children pc join public.users u on u.linked_student_id=pc.student_id
where pc.parent_username is not null and u.username is not null
on conflict (source_username,target_username,relation_type) do update set active=true,updated_at=now();

insert into public.school_relationships(source_username,source_role,target_username,target_role,relation_type)
select u.username,'student',pc.parent_username,'parent','student_parent'
from public.parent_children pc join public.users u on u.linked_student_id=pc.student_id
where pc.parent_username is not null and u.username is not null
on conflict (source_username,target_username,relation_type) do update set active=true,updated_at=now();
