-- Frahoosh smart classroom content channels.
-- Adds the persistent content streams used by the manager's smart-class monitor.
-- Idempotent: safe to apply after the existing online-class migrations.

create table if not exists public.smart_board_content (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  teacher_id bigint,
  title text,
  content text,
  content_type text not null default 'lesson',
  content_date_shamsi text,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_media (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  teacher_id bigint,
  media_type text not null default 'image',
  title text,
  url text,
  caption text,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_files (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  teacher_id bigint,
  file_name text not null,
  file_url text not null,
  file_type text not null default 'application/octet-stream',
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_chat (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  sender_user_id text,
  sender_name text,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_activity (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  teacher_id bigint,
  title text not null,
  activity_type text not null default 'activity',
  content text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_board_events (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  teacher_id bigint,
  event_type text not null default 'stroke',
  pen_size integer,
  shape_type text,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_notifications (
  id bigint generated by default as identity primary key,
  class_id bigint references public.online_classes(id) on delete cascade,
  student_id bigint,
  audience_role text,
  title text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_smart_board_content_class on public.smart_board_content(class_id, id desc);
create index if not exists idx_smart_board_media_class on public.smart_board_media(class_id, id desc);
create index if not exists idx_smart_board_files_class on public.smart_board_files(class_id, id desc);
create index if not exists idx_online_class_chat_class on public.online_class_chat(class_id, id desc);
create index if not exists idx_online_class_activity_class on public.online_class_activity(class_id, id desc);
create index if not exists idx_online_class_board_events_class on public.online_class_board_events(class_id, id desc);
create index if not exists idx_online_class_notifications_class on public.online_class_notifications(class_id, id desc);

do $$ declare t text; begin
  foreach t in array array[
    'smart_board_content','smart_board_media','smart_board_files','online_class_chat',
    'online_class_activity','online_class_board_events','online_class_notifications'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists frahoosh_authenticated_all on public.%I', t);
    execute format('create policy frahoosh_authenticated_all on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;
