-- Frahoosh canonical ZIP module tables
-- Source: Frahoosh_v16_12_LOGIN_BACKGROUND_FINAL_02.zip
-- Keeps Web and Android on the same module/table vocabulary.
-- Idempotent: safe for existing deployments.

create table if not exists public.teacher_attendance (
  id bigint generated by default as identity primary key,
  class_id bigint,
  student_id bigint,
  student_name text,
  teacher_id bigint,
  class_name text,
  subject text,
  status text,
  note text,
  description text,
  attendance_date text,
  recorded_at timestamptz not null default now()
);

create table if not exists public.grade_items (
  id bigint generated by default as identity primary key,
  student_id bigint,
  teacher_id bigint,
  subject text,
  grade_type text,
  term text,
  score numeric,
  grade_date text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.educational_activities (
  id bigint generated by default as identity primary key,
  title text,
  subject text,
  grade text,
  class_name text,
  teacher_id bigint,
  student_id bigint,
  activity_date text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.executive_classes (
  id bigint generated by default as identity primary key,
  name text,
  grade text,
  teacher text,
  created_at timestamptz not null default now()
);

create table if not exists public.executive_operations (
  id bigint generated by default as identity primary key,
  operation_type text,
  title text,
  student_id bigint,
  class_name text,
  status text,
  operation_date text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.executive_reports (
  id bigint generated by default as identity primary key,
  title text,
  report_type text,
  student_id bigint,
  class_name text,
  report_date text,
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.cultural_activity_registrations (
  id bigint generated by default as identity primary key,
  student_id bigint,
  activity_id bigint,
  activity_title text,
  activity_kind text,
  fee numeric default 0,
  payment_status text,
  registration_date text,
  created_at timestamptz not null default now()
);

create table if not exists public.competitions (
  id bigint generated by default as identity primary key,
  title text,
  category text,
  start_date text,
  end_date text,
  status text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.cultural_reports (
  id bigint generated by default as identity primary key,
  title text,
  report_type text,
  activity_id bigint,
  report_date text,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_content (
  id bigint generated by default as identity primary key,
  title text,
  content text,
  class_id bigint,
  teacher_id bigint,
  content_date_shamsi text,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_files (
  id bigint generated by default as identity primary key,
  title text,
  file_path text,
  file_type text,
  class_id bigint,
  teacher_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_media (
  id bigint generated by default as identity primary key,
  title text,
  media_path text,
  media_type text,
  class_id bigint,
  teacher_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_quizzes (
  id bigint generated by default as identity primary key,
  title text,
  question text,
  correct_option text,
  class_id bigint,
  teacher_id bigint,
  quiz_date_shamsi text,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_activities (
  id bigint generated by default as identity primary key,
  title text,
  activity_text text,
  class_id bigint,
  teacher_id bigint,
  activity_date_shamsi text,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_interactive_tools (
  id bigint generated by default as identity primary key,
  title text,
  tool_type text,
  content text,
  class_id bigint,
  teacher_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_assistant_sessions (
  id bigint generated by default as identity primary key,
  username text,
  role text,
  title text,
  request_date_shamsi text,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_questions (
  id bigint generated by default as identity primary key,
  username text,
  role text,
  question text,
  answer text,
  answer_date_shamsi text,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_educational_analysis (
  id bigint generated by default as identity primary key,
  student_id bigint,
  teacher_id bigint,
  subject text,
  period text,
  score numeric,
  risk_level text,
  analysis_date_shamsi text,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_smart_reports (
  id bigint generated by default as identity primary key,
  title text,
  report_type text,
  target_type text,
  target_id bigint,
  created_by text,
  report_date_shamsi text,
  created_at timestamptz not null default now()
);

create table if not exists public.counseling_records (
  id bigint generated by default as identity primary key,
  student_id bigint,
  title text,
  description text,
  status text default 'در حال پیگیری',
  created_at timestamptz not null default now()
);

create table if not exists public.counseling_followups (
  id bigint generated by default as identity primary key,
  student_id bigint,
  followup_date text,
  followup_items text,
  decision text,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.counseling_guidance (
  id bigint generated by default as identity primary key,
  student_id bigint,
  grade text,
  interest text,
  aptitude text,
  recommendation text,
  created_at timestamptz not null default now()
);

create table if not exists public.vice_referrals (
  id bigint generated by default as identity primary key,
  student_id bigint,
  teacher text,
  reason text,
  status text,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.vice_meetings (
  id bigint generated by default as identity primary key,
  title text,
  requester text,
  date text,
  status text default 'pending',
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.vice_notifications (
  id bigint generated by default as identity primary key,
  title text,
  body text,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_meetings (
  id bigint generated by default as identity primary key,
  teacher_id bigint,
  teacher_name text,
  student_id bigint,
  student_name text,
  parent_name text,
  meeting_at text,
  subject text,
  status text default 'requested',
  report text,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_activities (
  id bigint generated by default as identity primary key,
  teacher_id bigint,
  title text,
  activity_type text,
  description text,
  activity_date text,
  created_at timestamptz not null default now()
);

create table if not exists public.transport_requests (
  id bigint generated by default as identity primary key,
  parent_username text,
  address text,
  vehicle_type text,
  origin text,
  destination text,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.surveys (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  active boolean default true,
  created_at timestamptz not null default now()
);

create table if not exists public.survey_questions (
  id bigint generated by default as identity primary key,
  survey_id bigint,
  question text,
  question_type text,
  options jsonb default '[]'::jsonb,
  required boolean default true,
  sort_order integer default 0
);

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  survey_id bigint,
  respondent_username text,
  respondent_role text,
  student_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.survey_answers (
  id bigint generated by default as identity primary key,
  response_id bigint,
  question_id bigint,
  answer text
);

create table if not exists public.archive_items (
  id bigint generated by default as identity primary key,
  title text,
  student_id bigint,
  location text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.counselor_board (
  id bigint generated by default as identity primary key,
  title text,
  body text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.counseling_classes (
  id bigint generated by default as identity primary key,
  title text,
  grade text,
  subject text,
  teacher_id bigint,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cultural_competitions (
  id bigint generated by default as identity primary key,
  title text,
  category text,
  start_date text,
  end_date text,
  status text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.backup_records (
  id bigint generated by default as identity primary key,
  title text,
  backup_path text,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.parent_activities (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  activity_date text,
  status text,
  created_at timestamptz not null default now()
);

-- Fields used by the ZIP's special workspaces when an older table already exists.
alter table public.smart_board_whiteboards add column if not exists title text;
alter table public.smart_board_whiteboards add column if not exists teacher_id bigint;
alter table public.smart_board_whiteboards add column if not exists board_date text;

alter table public.finance_transactions add column if not exists invoice_number text;
alter table public.finance_transactions add column if not exists debit numeric default 0;
alter table public.finance_transactions add column if not exists credit numeric default 0;
alter table public.finance_transactions add column if not exists counterparty text;

-- The canonical Web/ZIP workflow uses these records as read/write operational data.
do $$
declare t text;
begin
  foreach t in array array[
    'teacher_attendance','grade_items','educational_activities','executive_classes',
    'executive_operations','executive_reports','cultural_activity_registrations',
    'competitions','cultural_reports','smart_board_content','smart_board_files',
    'smart_board_media','smart_board_quizzes','smart_board_activities',
    'smart_board_interactive_tools','ai_assistant_sessions','ai_questions',
    'ai_educational_analysis','ai_smart_reports','counseling_records',
    'counseling_followups','counseling_guidance','vice_referrals','vice_meetings',
    'vice_notifications','teacher_meetings','teacher_activities','archive_items','counselor_board','counseling_classes','cultural_competitions','backup_records','transport_requests',
    'surveys','survey_questions','survey_responses','survey_answers','parent_activities'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists frahoosh_canonical_authenticated on public.%I', t);
    execute format('create policy frahoosh_canonical_authenticated on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;
