-- Frahoosh: unified parent/teacher/staff/advisor meetings + manager/educational workflow.
-- Safe/idempotent schema. Run after the existing school workflow migrations.

create table if not exists public.meeting_requests (
  id bigint generated by default as identity primary key,
  requester_user_id text,
  requester_username text,
  requester_role text not null,
  student_id bigint,
  student_name text,
  parent_username text,
  parent_name text,
  target_user_id text,
  target_role text not null,
  target_name text not null,
  requested_date_shamsi text not null,
  requested_time text not null,
  reason text not null,
  description text,
  manager_status text not null default 'pending',
  manager_reviewed_by text,
  manager_reviewed_at timestamptz,
  manager_note text,
  educational_status text not null default 'pending',
  educational_reviewed_by text,
  educational_reviewed_at timestamptz,
  educational_note text,
  final_date_shamsi text,
  final_time text,
  final_note text,
  status text not null default 'pending_manager',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_meeting_requests_requester on public.meeting_requests(requester_username);
create index if not exists idx_meeting_requests_student on public.meeting_requests(student_id);
create index if not exists idx_meeting_requests_target on public.meeting_requests(target_user_id);
create index if not exists idx_meeting_requests_status on public.meeting_requests(status);

create table if not exists public.meeting_request_notifications (
  id bigint generated by default as identity primary key,
  meeting_id bigint references public.meeting_requests(id) on delete cascade,
  recipient_username text not null,
  recipient_role text,
  title text not null,
  body text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.frahoosh_meeting_create(
  p_requester_role text,
  p_requester_username text,
  p_student_id bigint,
  p_student_name text,
  p_parent_username text,
  p_parent_name text,
  p_target_user_id text,
  p_target_role text,
  p_target_name text,
  p_requested_date_shamsi text,
  p_requested_time text,
  p_reason text,
  p_description text default null
) returns bigint
language plpgsql security definer set search_path=public,private
as $$
declare v_id bigint; v_role text;
begin
  v_role := lower(coalesce((select private.frahoosh_current_role()), ''));
  if v_role = '' then
    raise exception 'کاربر احراز هویت نشده است';
  end if;
  if lower(coalesce(p_requester_role,'')) <> v_role and v_role not in ('مدیر','مدیریت','manager') then
    raise exception 'نقش درخواست‌دهنده معتبر نیست';
  end if;
  if nullif(trim(coalesce(p_target_name,'')),'') is null
     or nullif(trim(coalesce(p_requested_date_shamsi,'')),'') is null
     or nullif(trim(coalesce(p_requested_time,'')),'') is null
     or nullif(trim(coalesce(p_reason,'')),'') is null then
    raise exception 'فیلدهای ملاقات کامل نیستند';
  end if;

  insert into public.meeting_requests(
    requester_user_id, requester_username, requester_role,
    student_id, student_name, parent_username, parent_name,
    target_user_id, target_role, target_name,
    requested_date_shamsi, requested_time, reason, description
  ) values (
    auth.uid()::text, p_requester_username, p_requester_role,
    p_student_id, p_student_name, p_parent_username, p_parent_name,
    p_target_user_id, p_target_role, p_target_name,
    p_requested_date_shamsi, p_requested_time, p_reason, p_description
  ) returning id into v_id;
  return v_id;
end $$;

create or replace function public.frahoosh_meeting_manager_review(
  p_meeting_id bigint, p_approve boolean, p_note text default null
) returns boolean
language plpgsql security definer set search_path=public,private
as $$
declare v_role text;
begin
  v_role := lower(coalesce((select private.frahoosh_current_role()), ''));
  if v_role not in ('مدیر','مدیریت','manager') then raise exception 'فقط مدیر مجاز است'; end if;
  update public.meeting_requests
     set manager_status=case when p_approve then 'approved' else 'rejected' end,
         manager_reviewed_by=coalesce(auth.jwt()->>'email','manager'),
         manager_reviewed_at=now(),
         manager_note=p_note,
         status=case when p_approve then 'referred_to_educational' else 'rejected_manager' end,
         updated_at=now()
   where id=p_meeting_id;
  if not found then raise exception 'درخواست ملاقات پیدا نشد'; end if;
  return true;
end $$;

create or replace function public.frahoosh_meeting_educational_review(
  p_meeting_id bigint, p_approve boolean, p_final_date_shamsi text default null,
  p_final_time text default null, p_note text default null
) returns boolean
language plpgsql security definer set search_path=public,private
as $$
declare v_role text;
begin
  v_role := lower(coalesce((select private.frahoosh_current_role()), ''));
  if v_role not in ('معاون آموزشی','educational') then raise exception 'فقط معاون آموزشی مجاز است'; end if;
  update public.meeting_requests
     set educational_status=case when p_approve then 'approved' else 'rejected' end,
         educational_reviewed_by=coalesce(auth.jwt()->>'email','educational'),
         educational_reviewed_at=now(),
         educational_note=p_note,
         final_date_shamsi=case when p_approve then coalesce(nullif(trim(p_final_date_shamsi),''),requested_date_shamsi) else final_date_shamsi end,
         final_time=case when p_approve then coalesce(nullif(trim(p_final_time),''),requested_time) else final_time end,
         final_note=p_note,
         status=case when p_approve then 'confirmed' else 'rejected_educational' end,
         updated_at=now()
   where id=p_meeting_id and manager_status='approved';
  if not found then raise exception 'درخواست آماده ارجاع آموزشی نیست'; end if;
  return true;
end $$;

create or replace function public.frahoosh_meeting_notify(
  p_meeting_id bigint, p_recipient_username text, p_recipient_role text,
  p_title text, p_body text
) returns bigint
language plpgsql security definer set search_path=public,private
as $$
declare v_role text; v_id bigint;
begin
  v_role := lower(coalesce((select private.frahoosh_current_role()), ''));
  if v_role not in ('مدیر','مدیریت','manager','معاون آموزشی','educational') then
    raise exception 'دسترسی ارسال اعلان ملاقات مجاز نیست';
  end if;
  insert into public.meeting_request_notifications(meeting_id,recipient_username,recipient_role,title,body)
  values(p_meeting_id,p_recipient_username,p_recipient_role,p_title,p_body) returning id into v_id;
  return v_id;
end $$;

alter table public.meeting_requests enable row level security;
alter table public.meeting_request_notifications enable row level security;

drop policy if exists "meeting requests staff read" on public.meeting_requests;
create policy "meeting requests staff read" on public.meeting_requests
for select to authenticated
using (
  requester_username = coalesce(auth.jwt()->>'email','')
  or parent_username = coalesce(auth.jwt()->>'email','')
  or target_user_id = auth.uid()::text
  or (select private.frahoosh_current_role()) in (
    'مدیر','مدیریت','manager','معاون آموزشی','educational','معاون اجرایی','executive','معاون پرورشی','cultural','مشاوره','counselor','advisor','دبیر','teacher'
  )
);

drop policy if exists "meeting notifications own read" on public.meeting_request_notifications;
create policy "meeting notifications own read" on public.meeting_request_notifications
for select to authenticated
using (
  recipient_username = coalesce(auth.jwt()->>'email','')
  or (select private.frahoosh_current_role()) in ('مدیر','مدیریت','manager','معاون آموزشی','educational')
);

grant execute on function public.frahoosh_meeting_create(text,text,bigint,text,text,text,text,text,text,text,text,text,text) to authenticated;
grant execute on function public.frahoosh_meeting_manager_review(bigint,boolean,text) to authenticated;
grant execute on function public.frahoosh_meeting_educational_review(bigint,boolean,text,text,text) to authenticated;
grant execute on function public.frahoosh_meeting_notify(bigint,text,text,text,text) to authenticated;
