-- Frahoosh canonical core module tables
-- Source contract: Frahoosh_v16_12_LOGIN_BACKGROUND_FINAL_02.zip
-- Creates only core tables that were referenced by the shared Android/Web
-- catalog but were not guaranteed by the ZIP-specific migrations.
-- Idempotent: existing tables are preserved.

create table if not exists public.account_settings (
  id bigint generated by default as identity primary key,
  username text,
  display_name text,
  phone text,
  email text,
  preferences jsonb default '{}'::jsonb,
  national_code text,
  updated_at timestamptz not null default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  national_code text,
  student_code text,
  grade text,
  class_name text,
  phone text,
  parent_phone text,
  photo text,
  father_name text,
  mother_name text,
  birth_date text,
  email text,
  address text,
  description text,
  nationality text,
  religion text,
  sect text,
  created_at timestamptz not null default now()
);

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  national_code text,
  phone text,
  email text,
  subject text,
  grades text,
  description text,
  source_staff_id bigint,
  mobile text,
  lessons text,
  employment_status text,
  employee_code text,
  created_at timestamptz not null default now()
);

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  role text,
  phone text,
  description text,
  work_experience text,
  employee_code text,
  national_code text,
  religion text,
  sect text,
  children_count integer default 0,
  employment_status text,
  teaching_hours numeric default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique,
  role text,
  permissions jsonb default '{}'::jsonb,
  linked_student_id bigint,
  linked_teacher_id bigint,
  linked_staff_id bigint,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.parent_children (
  id bigint generated by default as identity primary key,
  parent_username text not null,
  student_id bigint not null,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_classes (
  id bigint generated by default as identity primary key,
  teacher_id bigint,
  teacher_name text,
  subject text,
  grade text,
  class_name text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint,
  date text,
  status text,
  description text,
  teacher_id bigint,
  subject text,
  class_name text,
  attendance_date text,
  created_at timestamptz not null default now()
);

create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  student_id bigint,
  teacher_id bigint,
  subject text,
  exam_name text,
  score numeric,
  description text,
  grade_type text,
  term text,
  max_score numeric default 20,
  grade_date text,
  title text,
  assessment_date text,
  created_at timestamptz not null default now()
);

create table if not exists public.student_grades (
  id bigint generated by default as identity primary key,
  student_id bigint,
  teacher_id bigint,
  subject text,
  class_name text,
  assessment_type text,
  assessment_title text,
  score numeric,
  coefficient numeric default 1,
  grade_date text,
  grade_date_shamsi text,
  description text,
  term text,
  manager_released boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  student_id bigint,
  teacher_id bigint,
  title text,
  description text,
  status text,
  due_date text,
  subject text,
  class_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.weekly_schedule (
  id bigint generated by default as identity primary key,
  teacher text,
  hours text,
  grade text,
  class_count integer default 0,
  subject text,
  bell_pattern text,
  class_names text,
  teacher_id bigint,
  weekdays text,
  created_at timestamptz not null default now()
);

create table if not exists public.generated_weekly_schedule (
  id bigint generated by default as identity primary key,
  source_id bigint,
  teacher text,
  subject text,
  grade text,
  class_name text,
  weekday text,
  bell text,
  week_index integer default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.exam_schedule (
  id bigint generated by default as identity primary key,
  subject text,
  grade text,
  start_date text,
  end_date text,
  weight numeric default 1,
  exam_date text,
  duration integer,
  exam_start_time text,
  exam_end_time text,
  created_at timestamptz not null default now()
);

create table if not exists public.online_attendance (
  id bigint generated by default as identity primary key,
  class_id bigint,
  student_id bigint,
  student_name text,
  status text,
  recorded_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender text,
  receiver text,
  text text,
  sender_user_id bigint,
  sender_name text,
  title text,
  body text,
  audience_type text,
  audience_value text,
  target_role text,
  target_name text,
  target_class_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.message_targets (
  id bigint generated by default as identity primary key,
  message_id bigint,
  target_role text,
  target_name text,
  target_class_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.message_reads (
  id bigint generated by default as identity primary key,
  message_id bigint,
  username text,
  read_at timestamptz
);

create table if not exists public.finance_accounts (
  id bigint generated by default as identity primary key,
  account_type text,
  account_number text,
  balance numeric default 0,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.finance_transactions (
  id bigint generated by default as identity primary key,
  transaction_type text,
  title text,
  amount numeric default 0,
  invoice_number text,
  debit numeric default 0,
  credit numeric default 0,
  counterparty text,
  category text,
  description text,
  transaction_date text,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_offers (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  amount numeric default 0,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_attempts (
  id bigint generated by default as identity primary key,
  offer_id bigint,
  username text,
  amount numeric default 0,
  gateway text,
  status text,
  reference text,
  authority text,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_records (
  id bigint generated by default as identity primary key,
  student_id bigint,
  parent_username text,
  title text,
  amount numeric default 0,
  status text,
  payment_date text,
  reference text,
  authority text,
  created_at timestamptz not null default now()
);

create table if not exists public.report_cards (
  id bigint generated by default as identity primary key,
  student_id bigint,
  term text,
  average numeric,
  description text,
  grade_level text,
  academic_year text,
  report_date text,
  created_at timestamptz not null default now()
);

create table if not exists public.report_card_snapshots (
  id bigint generated by default as identity primary key,
  student_id bigint,
  term text,
  snapshot_data jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.school_profile (
  id bigint generated by default as identity primary key,
  school_name text,
  school_code text,
  principal_name text,
  phone text,
  address text,
  academic_year text,
  logo_path text,
  request_date_shamsi text,
  created_at timestamptz not null default now()
);

create table if not exists public.parent_meetings (
  id bigint generated by default as identity primary key,
  student_id bigint,
  teacher_id bigint,
  parent_phone text,
  reason text,
  meeting_date text,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.school_events (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  event_date text,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_class_preview (
  id bigint generated by default as identity primary key,
  title text,
  class_id bigint,
  status text,
  created_at timestamptz not null default now()
);

-- Preserve existing installations while guaranteeing the fields used by the
-- shared contract are present.
alter table if exists public.users add column if not exists permissions jsonb default '{}'::jsonb;
alter table if exists public.users add column if not exists linked_student_id bigint;
alter table if exists public.users add column if not exists linked_teacher_id bigint;
alter table if exists public.users add column if not exists linked_staff_id bigint;
alter table if exists public.users add column if not exists display_name text;
alter table if exists public.students add column if not exists student_code text;
alter table if exists public.students add column if not exists parent_phone text;
alter table if exists public.students add column if not exists photo text;
alter table if exists public.students add column if not exists mother_name text;
alter table if exists public.students add column if not exists birth_date text;
alter table if exists public.students add column if not exists email text;
alter table if exists public.students add column if not exists address text;
alter table if exists public.students add column if not exists description text;
alter table if exists public.teachers add column if not exists employee_code text;
alter table if exists public.teacher_classes add column if not exists active boolean default true;
alter table if exists public.weekly_schedule add column if not exists teacher_id bigint;
alter table if exists public.weekly_schedule add column if not exists weekdays text;
alter table if exists public.report_cards add column if not exists grade_level text;
alter table if exists public.report_cards add column if not exists academic_year text;
alter table if exists public.report_cards add column if not exists report_date text;

-- New tables are deliberately usable by authenticated Web/Android clients.
-- Existing tables retain the application's existing RLS policies.
do $$
declare
  t text;
begin
  foreach t in array array[
    'account_settings','students','teachers','staff','users','parent_children',
    'teacher_classes','attendance','grades','student_grades','assignments',
    'weekly_schedule','generated_weekly_schedule','exam_schedule','online_attendance',
    'messages','message_targets','message_reads','finance_accounts','finance_transactions',
    'payment_offers','payment_attempts','payment_records','report_cards',
    'report_card_snapshots','school_profile','parent_meetings','school_events',
    'smart_class_preview'
  ] loop
    if to_regclass('public.' || t) is not null then
      execute format('alter table public.%I enable row level security', t);
      execute format('drop policy if exists frahoosh_core_authenticated on public.%I', t);
      execute format('create policy frahoosh_core_authenticated on public.%I for all to authenticated using (true) with check (true)', t);
    end if;
  end loop;
end $$;
