create table if not exists public.school_relationships(
 id bigint generated by default as identity primary key,
 source_username text not null,target_username text not null,target_role text,
 relationship_type text not null default 'school',active boolean not null default true,
 created_at timestamptz not null default now(),unique(source_username,target_username,relationship_type)
);
alter table public.school_relationships enable row level security;
drop policy if exists school_relationships_source_read on public.school_relationships;
create policy school_relationships_source_read on public.school_relationships for select to authenticated using(
 lower(source_username) in(select lower(coalesce(username,'')) from public.account_settings where auth_user_id=auth.uid())
 or private.frahoosh_is_staff()
);
drop policy if exists school_relationships_staff_all on public.school_relationships;
create policy school_relationships_staff_all on public.school_relationships for all to authenticated
using(private.frahoosh_is_staff()) with check(private.frahoosh_is_staff());
create index if not exists idx_school_relationships_source on public.school_relationships(source_username,active);
create index if not exists idx_school_relationships_target on public.school_relationships(target_username,active);
create or replace function public.refresh_school_relationships_for(p_source_username text)
returns integer language plpgsql security definer set search_path=public as $$
declare src record; target record; inserted_count integer:=0;
begin
 select * into src from public.account_settings where lower(username)=lower(p_source_username) limit 1;
 if not found then return 0; end if;
 delete from public.school_relationships where lower(source_username)=lower(src.username);
 for target in select username,role from public.account_settings where lower(username)<>lower(src.username) and lower(role)='manager' loop
  insert into public.school_relationships(source_username,target_username,target_role,relationship_type) values(src.username,target.username,target.role,'management') on conflict do nothing;
  inserted_count:=inserted_count+1;
 end loop;
 if lower(src.role) in('manager','educational','executive','cultural','advisor','counselor') then
  for target in select username,role from public.account_settings where lower(username)<>lower(src.username)
   and lower(role) in('student','parent','teacher','educational','executive','cultural','advisor','counselor') loop
   insert into public.school_relationships(source_username,target_username,target_role,relationship_type)
   values(src.username,target.username,target.role,'staff_directory') on conflict do nothing;
   inserted_count:=inserted_count+1;
  end loop;
 elsif lower(src.role)='teacher' then
  for target in
   select distinct a.username,a.role from public.account_settings a join public.students s on s.national_code=a.national_code
   join public.teacher_classes tc on lower(coalesce(tc.class_name,''))=lower(coalesce(s.class_name,''))
    and lower(coalesce(tc.grade,''))=lower(coalesce(s.grade,''))
   join public.teachers t on t.id=tc.teacher_id
   where lower(a.role)='student' and lower(coalesce(t.national_code,''))=lower(coalesce(src.national_code,''))
  loop
   insert into public.school_relationships(source_username,target_username,target_role,relationship_type)
   values(src.username,target.username,target.role,'teaching') on conflict do nothing; inserted_count:=inserted_count+1;
  end loop;
  for target in
   select distinct a.username,a.role from public.account_settings a join public.parent_children pc on lower(pc.parent_username)=lower(a.national_code)
   join public.students s on s.id=pc.student_id join public.teacher_classes tc on lower(coalesce(tc.class_name,''))=lower(coalesce(s.class_name,''))
    and lower(coalesce(tc.grade,''))=lower(coalesce(s.grade,'')) join public.teachers t on t.id=tc.teacher_id
   where lower(a.role)='parent' and lower(coalesce(t.national_code,''))=lower(coalesce(src.national_code,''))
  loop
   insert into public.school_relationships(source_username,target_username,target_role,relationship_type)
   values(src.username,target.username,target.role,'parent_of_student') on conflict do nothing; inserted_count:=inserted_count+1;
  end loop;
 elsif lower(src.role)='student' then
  for target in select distinct a.username,a.role from public.account_settings a join public.parent_children pc on lower(pc.parent_username)=lower(a.national_code)
   join public.students s on s.id=pc.student_id where lower(a.role)='parent' and s.national_code=src.national_code loop
   insert into public.school_relationships(source_username,target_username,target_role,relationship_type)
   values(src.username,target.username,target.role,'parent') on conflict do nothing; inserted_count:=inserted_count+1;
  end loop;
  for target in select distinct a.username,a.role from public.account_settings a join public.teachers t on t.national_code=a.national_code
   join public.teacher_classes tc on tc.teacher_id=t.id join public.students s on lower(coalesce(tc.class_name,''))=lower(coalesce(s.class_name,''))
    and lower(coalesce(tc.grade,''))=lower(coalesce(s.grade,'')) where lower(a.role)='teacher' and s.national_code=src.national_code loop
   insert into public.school_relationships(source_username,target_username,target_role,relationship_type)
   values(src.username,target.username,target.role,'teacher') on conflict do nothing; inserted_count:=inserted_count+1;
  end loop;
 elsif lower(src.role)='parent' then
  for target in select distinct a.username,a.role from public.account_settings a join public.students s on s.national_code=a.national_code
   join public.parent_children pc on pc.student_id=s.id where lower(a.role)='student' and lower(pc.parent_username)=lower(src.national_code) loop
   insert into public.school_relationships(source_username,target_username,target_role,relationship_type)
   values(src.username,target.username,target.role,'child') on conflict do nothing; inserted_count:=inserted_count+1;
  end loop;
  for target in select distinct a.username,a.role from public.account_settings a join public.teachers t on t.national_code=a.national_code
   join public.teacher_classes tc on tc.teacher_id=t.id join public.students s on lower(coalesce(tc.class_name,''))=lower(coalesce(s.class_name,''))
    and lower(coalesce(tc.grade,''))=lower(coalesce(s.grade,'')) join public.parent_children pc on pc.student_id=s.id
   where lower(a.role)='teacher' and lower(pc.parent_username)=lower(src.national_code) loop
   insert into public.school_relationships(source_username,target_username,target_role,relationship_type)
   values(src.username,target.username,target.role,'child_teacher') on conflict do nothing; inserted_count:=inserted_count+1;
  end loop;
 end if;
 return inserted_count;
end; $$;
revoke all on function public.refresh_school_relationships_for(text) from public;
grant execute on function public.refresh_school_relationships_for(text) to service_role;
create or replace function public.refresh_all_school_relationships() returns integer language plpgsql security definer set search_path=public as $$
declare r record;n integer:=0; begin for r in select username from public.account_settings where username is not null loop n:=n+public.refresh_school_relationships_for(r.username); end loop; return n; end; $$;
revoke all on function public.refresh_all_school_relationships() from public; grant execute on function public.refresh_all_school_relationships() to service_role;
create or replace function public.trg_refresh_school_relationships() returns trigger language plpgsql security definer set search_path=public as $$
begin perform public.refresh_school_relationships_for(new.username); return new; end; $$;
drop trigger if exists trg_account_settings_relationships on public.account_settings;
create trigger trg_account_settings_relationships after insert or update of username,national_code,role on public.account_settings for each row execute function public.trg_refresh_school_relationships();
drop policy if exists message_reads_own_insert on public.message_reads;
create policy message_reads_own_insert on public.message_reads for insert to authenticated with check(
 lower(coalesce(username,'')) in(select lower(coalesce(username,'')) from public.account_settings where auth_user_id=auth.uid())
);
drop policy if exists message_reads_own_select on public.message_reads;
create policy message_reads_own_select on public.message_reads for select to authenticated using(
 lower(coalesce(username,'')) in(select lower(coalesce(username,'')) from public.account_settings where auth_user_id=auth.uid())
 or private.frahoosh_is_staff()
);
select public.refresh_all_school_relationships();