-- Frahoosh school meeting workflow.
-- Parents, teachers, staff and counselors can request meetings.
-- Manager approval is followed by educational-deputy review.
-- All records live in Supabase and are protected by role/recipient RLS.

create table if not exists public.school_meeting_requests (
  id bigint generated by default as identity primary key,
  requester_id bigint,
  requester_username text not null,
  requester_role text not null,
  student_id bigint,
  student_name text,
  target_role text not null,
  target_name text not null,
  target_username text,
  requested_date_shamsi text not null,
  requested_time text not null,
  reason text not null,
  status text not null default 'pending_manager',
  manager_status text not null default 'pending',
  educational_status text not null default 'pending',
  manager_approved_at timestamptz,
  educational_approved_at timestamptz,
  manager_note text,
  educational_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_school_meeting_requester on public.school_meeting_requests(requester_username);
create index if not exists idx_school_meeting_target on public.school_meeting_requests(target_username);
create index if not exists idx_school_meeting_status on public.school_meeting_requests(status);
create index if not exists idx_school_meeting_student on public.school_meeting_requests(student_id);

create table if not exists public.school_notifications (
  id bigint generated by default as identity primary key,
  recipient_username text not null,
  title text not null,
  body text not null,
  related_type text,
  related_id bigint,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_school_notifications_recipient on public.school_notifications(recipient_username,is_read,created_at desc);

alter table public.school_meeting_requests enable row level security;
alter table public.school_notifications enable row level security;

drop policy if exists school_meeting_manager_all on public.school_meeting_requests;
create policy school_meeting_manager_all on public.school_meeting_requests
for all to authenticated
using ((select private.frahoosh_current_role()) = any(array['مدیر','مدیریت','manager']))
with check ((select private.frahoosh_current_role()) = any(array['مدیر','مدیریت','manager']));

drop policy if exists school_meeting_educational_read on public.school_meeting_requests;
create policy school_meeting_educational_read on public.school_meeting_requests
for select to authenticated
using ((select private.frahoosh_current_role()) = any(array['معاون آموزشی','educational']));

drop policy if exists school_meeting_educational_update on public.school_meeting_requests;
create policy school_meeting_educational_update on public.school_meeting_requests
for update to authenticated
using ((select private.frahoosh_current_role()) = any(array['معاون آموزشی','educational']))
with check ((select private.frahoosh_current_role()) = any(array['معاون آموزشی','educational']));

drop policy if exists school_meeting_owner_read on public.school_meeting_requests;
create policy school_meeting_owner_read on public.school_meeting_requests
for select to authenticated
using (
  lower(requester_username)=lower(coalesce(auth.jwt()->>'email',''))
  or lower(coalesce(target_username,''))=lower(coalesce(auth.jwt()->>'email',''))
);

drop policy if exists school_meeting_request_insert on public.school_meeting_requests;
create policy school_meeting_request_insert on public.school_meeting_requests
for insert to authenticated
with check (
  lower(requester_username)=lower(coalesce(auth.jwt()->>'email',''))
  and lower(requester_role) = lower(coalesce((select private.frahoosh_current_role()),''))
);

drop policy if exists school_notifications_recipient_read on public.school_notifications;
create policy school_notifications_recipient_read on public.school_notifications
for select to authenticated
using (lower(recipient_username)=lower(coalesce(auth.jwt()->>'email','')));

drop policy if exists school_notifications_recipient_update on public.school_notifications;
create policy school_notifications_recipient_update on public.school_notifications
for update to authenticated
using (lower(recipient_username)=lower(coalesce(auth.jwt()->>'email','')))
with check (lower(recipient_username)=lower(coalesce(auth.jwt()->>'email','')));

create or replace function public.frahoosh_notify_meeting_change()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.school_notifications(recipient_username,title,body,related_type,related_id)
    select u.username,
      'درخواست ملاقات جدید',
      coalesce(new.student_name,'دانش‌آموز') || ' — ' || new.target_name || ' | ' || new.requested_date_shamsi || ' ' || new.requested_time,
      'school_meeting',
      new.id
    from public.users u
    where lower(coalesce(u.role,'')) in ('مدیر','مدیریت','manager');
    return new;
  end if;

  if new.status is distinct from old.status then
    if new.status = 'pending_educational' then
      insert into public.school_notifications(recipient_username,title,body,related_type,related_id)
      select u.username,'ارجاع درخواست ملاقات به معاون آموزشی',
             coalesce(new.student_name,'دانش‌آموز') || ' — ' || new.target_name,
             'school_meeting',new.id
      from public.users u
      where lower(coalesce(u.role,'')) in ('معاون آموزشی','educational');
    elsif new.status in ('confirmed','rejected') then
      if nullif(new.requester_username,'') is not null then
        insert into public.school_notifications(recipient_username,title,body,related_type,related_id)
        values (new.requester_username,'تغییر وضعیت درخواست ملاقات',
                'وضعیت درخواست شما: ' || new.status,
                'school_meeting',new.id);
      end if;
      if nullif(new.target_username,'') is not null then
        insert into public.school_notifications(recipient_username,title,body,related_type,related_id)
        values (new.target_username,'تغییر وضعیت ملاقات',
                'وضعیت ملاقات: ' || new.status,
                'school_meeting',new.id);
      end if;
    end if;
  end if;
  new.updated_at=now();
  return new;
end;
$$;

drop trigger if exists trg_frahoosh_meeting_change on public.school_meeting_requests;
create trigger trg_frahoosh_meeting_change
before insert or update on public.school_meeting_requests
for each row execute function public.frahoosh_notify_meeting_change();
