-- Frahoosh: materialize every remaining supporting table present in the canonical ZIP school.db.
-- These are real backend tables used by the ZIP services/workflows, even when they are
-- not shown as standalone navigation cards. Web and Android can therefore share one
-- complete Supabase data model without decorative/nonexistent tables.

create table if not exists public.audience_presets (
  id bigint generated by default as identity primary key,
  name text,
  targets_json text,
  created_at timestamptz not null default now()
);

create table if not exists public.class_seats (
  id bigint generated by default as identity primary key,
  student_id bigint,
  class_name text,
  seat_no text,
  created_at timestamptz not null default now()
);

create table if not exists public.discipline_items (
  id bigint generated by default as identity primary key,
  title text,
  description text default '',
  deduction numeric default 0,
  active boolean default true,
  created_at timestamptz not null default now()
);

create table if not exists public.discipline_settings (
  id bigint generated by default as identity primary key,
  base_score numeric default 20,
  updated_at timestamptz not null default now()
);

create table if not exists public.event_audiences (
  id bigint generated by default as identity primary key,
  event_id bigint,
  target_type text,
  target_value text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.exam_cards (
  id bigint generated by default as identity primary key,
  student_id bigint,
  exam_name text,
  code text,
  created_at timestamptz not null default now()
);

create table if not exists public.exam_seats (
  id bigint generated by default as identity primary key,
  student_id bigint,
  exam_name text,
  seat_no text,
  created_at timestamptz not null default now()
);

create table if not exists public.finance_donations (
  id bigint generated by default as identity primary key,
  donor_name text,
  amount numeric default 0,
  description text,
  donation_date text
);

create table if not exists public.finance_extra (
  id bigint generated by default as identity primary key,
  title text,
  student_name text,
  amount numeric default 0,
  description text,
  payment_date text
);

create table if not exists public.grade_visibility (
  id bigint generated by default as identity primary key,
  grade_id bigint,
  released_by text default '',
  released_at_shamsi text default '',
  released boolean default false
);

create table if not exists public.message_delivery (
  id bigint generated by default as identity primary key,
  message_id bigint,
  username text,
  received_at text default '',
  seen_at text default ''
);

create table if not exists public.online_class_activity (
  id bigint generated by default as identity primary key,
  class_id bigint,
  session_id bigint,
  student_id bigint,
  event_type text,
  event_time text,
  metadata jsonb default '{}'::jsonb
);

create table if not exists public.online_class_ai_reports (
  id bigint generated by default as identity primary key,
  class_id bigint,
  student_id bigint,
  session_id bigint,
  report text,
  risk_level text default 'normal',
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_board_events (
  id bigint generated by default as identity primary key,
  class_id bigint,
  actor_id bigint,
  actor_role text default '',
  event_type text,
  payload jsonb default '{}'::jsonb,
  event_date_shamsi text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_notifications (
  id bigint generated by default as identity primary key,
  class_id bigint,
  student_id bigint,
  recipient text,
  recipient_role text,
  title text,
  message text,
  created_at timestamptz not null default now(),
  read_at text default ''
);

create table if not exists public.online_class_settings (
  class_id bigint primary key,
  public_chat_enabled boolean default false,
  private_chat_enabled boolean default true,
  board_enabled boolean default true,
  file_share_enabled boolean default true,
  media_enabled boolean default true,
  quiz_enabled boolean default true,
  camera_enabled boolean default true,
  microphone_enabled boolean default true,
  screen_share_enabled boolean default true,
  updated_at_shamsi text default ''
);

create table if not exists public.online_presence_checks (
  id bigint generated by default as identity primary key,
  class_id bigint,
  session_id bigint,
  student_id bigint,
  checkpoint_no integer,
  scheduled_at text,
  shown_at text default '',
  responded_at text default '',
  response text default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.online_quizzes (
  id bigint generated by default as identity primary key,
  class_id bigint,
  title text,
  subject text,
  duration integer default 0,
  teacher text,
  created_at timestamptz not null default now()
);

create table if not exists public.parent_dashboard_events (
  id bigint generated by default as identity primary key,
  parent_username text,
  student_id bigint,
  event_type text,
  source_table text default '',
  source_id bigint,
  title text default '',
  payload jsonb default '{}'::jsonb,
  seen_at text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  student_id bigint,
  registration_id bigint,
  amount numeric,
  gateway text default 'psp',
  authority text default '',
  reference text default '',
  status text default 'pending',
  created_at timestamptz not null default now(),
  paid_at text default '',
  parent_username text default '',
  payment_date text default ''
);

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  role text,
  module text,
  allowed boolean default false
);

create table if not exists public.seating (
  id bigint generated by default as identity primary key,
  student_id bigint,
  seat_no text,
  exam text,
  created_at timestamptz not null default now()
);

create table if not exists public.student_dashboard_events (
  id bigint generated by default as identity primary key,
  username text,
  student_id bigint,
  event_type text,
  source_table text default '',
  source_id bigint,
  title text default '',
  payload jsonb default '{}'::jsonb,
  seen_at text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.student_files (
  id bigint generated by default as identity primary key,
  student_id bigint,
  medical_notes text default '',
  educational_notes text default '',
  disciplinary_notes text default '',
  family_notes text default '',
  attachments jsonb default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.student_registrations (
  id bigint generated by default as identity primary key,
  student_id bigint,
  activity_id bigint,
  activity_title text,
  activity_kind text,
  fee numeric default 0,
  payment_status text default 'pending',
  payment_url text default '',
  payment_reference text default '',
  registration_code text,
  registered_at text,
  registration_date text default '',
  status text default 'active'
);

create table if not exists public.survey_answers (
  id bigint generated by default as identity primary key,
  response_id bigint,
  question_id bigint,
  answer text default ''
);

create table if not exists public.survey_questions (
  id bigint generated by default as identity primary key,
  survey_id bigint,
  question text,
  question_type text default 'text',
  options jsonb default '[]'::jsonb,
  required boolean default false,
  sort_order integer default 0
);

do $$
declare t text;
begin
  foreach t in array array[
    'audience_presets','class_seats','discipline_items','discipline_settings',
    'event_audiences','exam_cards','exam_seats','finance_donations','finance_extra',
    'grade_visibility','message_delivery','online_class_activity',
    'online_class_ai_reports','online_class_board_events','online_class_chat',
    'online_class_notifications','online_class_settings','online_presence_checks',
    'online_quizzes','parent_dashboard_events','payment_transactions','permissions',
    'seating','student_dashboard_events','student_files','student_registrations',
    'survey_answers','survey_questions'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists frahoosh_zip_support_authenticated on public.%I', t);
    execute format(
      'create policy frahoosh_zip_support_authenticated on public.%I for all to authenticated using (true) with check (true)',
      t
    );
  end loop;
end $$;
