-- Frahoosh: operationalize every visible module.
-- Creates missing canonical module tables, adds fields used by the shared Android
-- contract, and gives authenticated users access through the existing role/RLS
-- layer. Existing tables/data are preserved.

create table if not exists public.online_class_chat (
  id bigint generated by default as identity primary key,
  class_id bigint, session_id bigint, sender_id bigint, sender_name text,
  sender_role text, message text, created_at timestamptz not null default now()
);

create table if not exists public.executive_classes (
  id bigint generated by default as identity primary key,
  grade text, class_name text, capacity integer default 0, academic_year text,
  active boolean not null default true, description text, created_at timestamptz not null default now()
);
create table if not exists public.archive_items (
  id bigint generated by default as identity primary key,
  student_id bigint, title text, category text, description text, file_url text,
  status text, created_at timestamptz not null default now()
);
create table if not exists public.executive_operations (
  id bigint generated by default as identity primary key,
  title text, operation_type text, student_id bigint, description text, status text,
  operation_date text, created_at timestamptz not null default now()
);
create table if not exists public.executive_reports (
  id bigint generated by default as identity primary key,
  title text, report_type text, period text, report text, created_by text,
  report_date text, created_at timestamptz not null default now()
);
create table if not exists public.executive_requests (
  id bigint generated by default as identity primary key,
  requester_username text, requester_name text, request_type text, description text,
  status text, decision text, created_at timestamptz not null default now()
);

create table if not exists public.cultural_competitions (
  id bigint generated by default as identity primary key,
  title text, category text, grade text, class_name text, event_date text,
  capacity integer default 0, active boolean not null default true, description text,
  created_at timestamptz not null default now()
);
create table if not exists public.cultural_activity_registrations (
  id bigint generated by default as identity primary key,
  activity_id bigint, activity_title text, student_id bigint, student_name text,
  participation_type text, team_members text, competition_type text,
  payment_status text, registration_date text, status text,
  created_at timestamptz not null default now()
);
create table if not exists public.cultural_reports (
  id bigint generated by default as identity primary key,
  title text, report_type text, target_id bigint, report text, report_date text,
  created_by text, created_at timestamptz not null default now()
);
create table if not exists public.student_council (
  id bigint generated by default as identity primary key,
  student_id bigint, student_name text, position text, election_date text,
  votes integer default 0, status text, created_at timestamptz not null default now()
);
create table if not exists public.basij_registration (
  id bigint generated by default as identity primary key,
  student_id bigint, student_name text, registration_date text, status text,
  note text, created_at timestamptz not null default now()
);
create table if not exists public.school_ally (
  id bigint generated by default as identity primary key,
  student_id bigint, student_name text, responsibility text, start_date text,
  end_date text, status text, created_at timestamptz not null default now()
);
create table if not exists public.school_mayor (
  id bigint generated by default as identity primary key,
  student_id bigint, student_name text, election_date text, votes integer default 0,
  status text, created_at timestamptz not null default now()
);
create table if not exists public.art_competitions (
  id bigint generated by default as identity primary key,
  title text, category text, grade text, event_date text, student_id bigint,
  result text, status text, created_at timestamptz not null default now()
);
create table if not exists public.sport_competitions (
  id bigint generated by default as identity primary key,
  title text, category text, grade text, event_date text, student_id bigint,
  result text, status text, created_at timestamptz not null default now()
);
create table if not exists public.morning_leaders (
  id bigint generated by default as identity primary key,
  student_id bigint, student_name text, role text, ceremony_date text,
  status text, created_at timestamptz not null default now()
);
create table if not exists public.qari_registration (
  id bigint generated by default as identity primary key,
  student_id bigint, student_name text, ceremony_date text, status text,
  created_at timestamptz not null default now()
);

create table if not exists public.counselor_board (
  id bigint generated by default as identity primary key,
  title text, content text, category text, published boolean default false,
  created_by text, created_at timestamptz not null default now()
);
create table if not exists public.counseling_records (
  id bigint generated by default as identity primary key,
  student_id bigint, student_name text, visit_reason text, recommendations text,
  reason_summary text, next_visit text, status text, created_at timestamptz not null default now()
);
create table if not exists public.counseling_followups (
  id bigint generated by default as identity primary key,
  student_id bigint, subject text, description text, followup_date text,
  followup_items text, decision text, status text, created_at timestamptz not null default now()
);
create table if not exists public.counseling_classes (
  id bigint generated by default as identity primary key,
  title text, grade text, class_name text, topic text, counselor_id bigint,
  session_date text, status text, created_at timestamptz not null default now()
);
create table if not exists public.counseling_guidance (
  id bigint generated by default as identity primary key,
  student_id bigint, guidance_type text, recommendation text, destination text,
  score numeric, academic_year text, status text, created_at timestamptz not null default now()
);

create table if not exists public.teacher_activities (
  id bigint generated by default as identity primary key,
  teacher_id bigint, student_id bigint, title text, activity_type text,
  subject text, score numeric, description text, activity_date text,
  created_at timestamptz not null default now()
);
create table if not exists public.teacher_meetings (
  id bigint generated by default as identity primary key,
  teacher_id bigint, parent_id bigint, student_id bigint, requested_date text,
  requested_time text, reason text, status text, manager_status text,
  created_at timestamptz not null default now()
);

create table if not exists public.smart_board_content (
  id bigint generated by default as identity primary key,
  title text, content text, class_id bigint, teacher_id bigint,
  content_date_shamsi text, created_at timestamptz not null default now()
);
create table if not exists public.smart_board_activities (
  id bigint generated by default as identity primary key,
  title text, activity_text text, class_id bigint, teacher_id bigint,
  activity_date_shamsi text, created_at timestamptz not null default now()
);
create table if not exists public.smart_board_quizzes (
  id bigint generated by default as identity primary key,
  title text, question text, option_a text, option_b text, option_c text,
  option_d text, correct_option text, class_id bigint, teacher_id bigint,
  quiz_date_shamsi text, created_at timestamptz not null default now()
);
create table if not exists public.smart_board_files (
  id bigint generated by default as identity primary key,
  title text, file_url text, class_id bigint, teacher_id bigint,
  created_at timestamptz not null default now()
);
create table if not exists public.smart_board_media (
  id bigint generated by default as identity primary key,
  title text, media_type text, media_url text, class_id bigint, teacher_id bigint,
  created_at timestamptz not null default now()
);
create table if not exists public.smart_board_interactive_tools (
  id bigint generated by default as identity primary key,
  title text, tool_type text, configuration jsonb default '{}'::jsonb,
  class_id bigint, teacher_id bigint, created_at timestamptz not null default now()
);

create table if not exists public.ai_educational_analysis (
  id bigint generated by default as identity primary key,
  student_id bigint, class_name text, subject text, analysis text,
  risk_level text, created_by text, created_at timestamptz not null default now()
);

-- Ensure common operational fields exist on pre-existing tables.
alter table if exists public.online_classes
  add column if not exists title text,
  add column if not exists subject text,
  add column if not exists lesson text,
  add column if not exists teacher text,
  add column if not exists grade text,
  add column if not exists class_name text,
  add column if not exists duration integer,
  add column if not exists start_time text,
  add column if not exists end_time text,
  add column if not exists status text default 'draft',
  add column if not exists join_url text,
  add column if not exists meeting_url text,
  add column if not exists camera boolean default true,
  add column if not exists microphone boolean default true,
  add column if not exists smart_board boolean default true,
  add column if not exists quiz boolean default true;

alter table if exists public.teacher_exams
  add column if not exists teacher_id bigint,
  add column if not exists title text,
  add column if not exists subject text,
  add column if not exists grade text,
  add column if not exists class_name text,
  add column if not exists exam_type text,
  add column if not exists exam_date text,
  add column if not exists duration integer,
  add column if not exists description text,
  add column if not exists published boolean default false,
  add column if not exists secure_mode boolean default true,
  add column if not exists share_enabled boolean default false,
  add column if not exists share_code text,
  add column if not exists max_attempts integer default 1,
  add column if not exists passing_score numeric;

alter table if exists public.quiz_questions
  add column if not exists quiz_id bigint,
  add column if not exists question text,
  add column if not exists option1 text,
  add column if not exists option2 text,
  add column if not exists option3 text,
  add column if not exists option4 text,
  add column if not exists correct_answer text,
  add column if not exists points numeric default 1,
  add column if not exists question_type text default 'multiple_choice',
  add column if not exists options_json jsonb,
  add column if not exists accepted_answers text,
  add column if not exists explanation text,
  add column if not exists difficulty text,
  add column if not exists auto_grade boolean default true;

-- RLS: the application role policies decide who may write. These baseline
-- policies only make the newly materialized module tables reachable by
-- authenticated users; manager/teacher-specific policies can coexist.
do $$
declare t text;
begin
  foreach t in array array[
    'online_class_chat','executive_classes','archive_items','executive_operations',
    'executive_reports','executive_requests','cultural_competitions',
    'cultural_activity_registrations','cultural_reports','student_council',
    'basij_registration','school_ally','school_mayor','art_competitions',
    'sport_competitions','morning_leaders','qari_registration','counselor_board',
    'counseling_records','counseling_followups','counseling_classes',
    'counseling_guidance','teacher_activities','teacher_meetings',
    'smart_board_content','smart_board_activities','smart_board_quizzes',
    'smart_board_files','smart_board_media','smart_board_interactive_tools',
    'ai_educational_analysis'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists frahoosh_authenticated_operational on public.%I', t);
    execute format('create policy frahoosh_authenticated_operational on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- The existing manager full-CRUD migration will cover these tables when this
-- migration is applied after it; this grant also keeps the Data API exposed.
grant usage on schema public to authenticated;
