create table if not exists public.meeting_requests (
    id bigint generated by default as identity primary key,
    requester_username text,
    requester_name text,
    requester_role text,
    target_username text,
    target_name text,
    target_role text,
    student_id bigint,
    teacher_id bigint,
    parent_id bigint,
    parent_phone text,
    requested_date text,
    requested_time text,
    reason text,
    status text not null default 'pending_responsible',
    responsible_status text,
    manager_status text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_meeting_requests_status on public.meeting_requests(status);
create index if not exists idx_meeting_requests_requester on public.meeting_requests(requester_username);
create index if not exists idx_meeting_requests_target on public.meeting_requests(target_username);

alter table public.meeting_requests enable row level security;
drop policy if exists frahoosh_authenticated_all on public.meeting_requests;
create policy frahoosh_authenticated_all
on public.meeting_requests
for all to authenticated
using (true)
with check (true);