-- Frahoosh final consumer security + workflow hardening.
-- Schema prerequisites are applied before the RLS layer.
alter table public.payment_attempts
  add column if not exists payer_username text,
  add column if not exists payer_role text,
  add column if not exists student_id bigint,
  add column if not exists description text,
  add column if not exists gateway_ref text;

create table if not exists public.assignment_submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint,
  student_id bigint not null,
  file_url text,
  answer_text text,
  submitted_at timestamptz not null default now(),
  status text default 'submitted',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_assignment_submissions_student on public.assignment_submissions(student_id);
create index if not exists idx_assignment_submissions_assignment on public.assignment_submissions(assignment_id);

alter table if exists public.meeting_requests add column if not exists title text;

do $$
declare t text;
begin
  foreach t in array array[
    'students','teachers','staff','teacher_classes','attendance','grades','student_grades','assignments',
    'discipline_records','educational_followups','academic_followups','teacher_exams','quiz_questions',
    'online_classes','online_class_sessions','online_class_students','online_class_teachers',
    'smart_board_whiteboards','meeting_requests','school_events','report_cards','weekly_schedule',
    'exam_schedule','finance_accounts','finance_transactions','finance_donations','payment_offers',
    'payment_attempts','payment_records','payment_transactions','certificate_requests','archive_items',
    'assets','student_cards','class_cards','class_seat_assignments','exam_seat_assignments',
    'parent_children','parents','message_targets','message_reads','account_settings','messages',
    'assignment_submissions'
  ] loop
    if to_regclass('public.'||t) is not null then
      execute format('alter table public.%I enable row level security',t);
      execute format('drop policy if exists frahoosh_authenticated_all on public.%I',t);
      execute format('drop policy if exists frahoosh_authenticated_operational on public.%I',t);
      execute format('drop policy if exists frahoosh_manager_operational_write on public.%I',t);
    end if;
  end loop;
end $$;

do $$
declare t text;
begin
  foreach t in array array[
    'students','teachers','staff','teacher_classes','attendance','grades','student_grades','assignments',
    'discipline_records','educational_followups','academic_followups','teacher_exams','quiz_questions',
    'online_classes','online_class_sessions','online_class_students','online_class_teachers',
    'smart_board_whiteboards','meeting_requests','school_events','report_cards','weekly_schedule',
    'exam_schedule','finance_accounts','finance_transactions','finance_donations','payment_offers',
    'payment_attempts','payment_records','payment_transactions','certificate_requests','archive_items',
    'assets','student_cards','class_cards','class_seat_assignments','exam_seat_assignments',
    'parent_children','parents','message_targets','message_reads','account_settings','messages',
    'assignment_submissions'
  ] loop
    if to_regclass('public.'||t) is not null then
      execute format(
        'create policy frahoosh_staff_full on public.%I for all to authenticated
         using (coalesce((select private.frahoosh_current_role()),'''') not in
           (''student'',''parent'',''دانش‌آموز'',''ولی'',''اولیا''))
         with check (coalesce((select private.frahoosh_current_role()),'''') not in
           (''student'',''parent'',''دانش‌آموز'',''ولی'',''اولیا''))',t);
    end if;
  end loop;
end $$;

do $$
declare t text;
begin
  foreach t in array array[
    'students','teachers','staff','teacher_classes','attendance','grades','student_grades','assignments',
    'discipline_records','educational_followups','academic_followups','teacher_exams','quiz_questions',
    'online_classes','online_class_sessions','online_class_students','online_class_teachers',
    'smart_board_whiteboards','meeting_requests','school_events','report_cards','weekly_schedule',
    'exam_schedule','finance_accounts','finance_transactions','finance_donations','payment_offers',
    'payment_records','payment_transactions','certificate_requests','archive_items','assets',
    'student_cards','class_cards','class_seat_assignments','exam_seat_assignments','parent_children',
    'parents','message_targets','message_reads','messages','assignment_submissions'
  ] loop
    if to_regclass('public.'||t) is not null then
      execute format(
        'create policy frahoosh_consumer_read on public.%I for select to authenticated
         using ((select private.frahoosh_current_role()) in
           (''student'',''parent'',''دانش‌آموز'',''ولی'',''اولیا''))',t);
    end if;
  end loop;
end $$;

drop policy if exists frahoosh_student_submission_insert on public.assignment_submissions;
create policy frahoosh_student_submission_insert on public.assignment_submissions
for insert to authenticated
with check (
  (select private.frahoosh_current_role()) in ('student','دانش‌آموز')
  and student_id=(select private.frahoosh_current_student_id())
);

drop policy if exists frahoosh_student_submission_update on public.assignment_submissions;
create policy frahoosh_student_submission_update on public.assignment_submissions
for update to authenticated
using ((select private.frahoosh_current_role()) in ('student','دانش‌آموز')
       and student_id=(select private.frahoosh_current_student_id()))
with check ((select private.frahoosh_current_role()) in ('student','دانش‌آموز')
       and student_id=(select private.frahoosh_current_student_id()));

drop policy if exists frahoosh_student_submission_delete on public.assignment_submissions;
create policy frahoosh_student_submission_delete on public.assignment_submissions
for delete to authenticated
using ((select private.frahoosh_current_role()) in ('student','دانش‌آموز')
       and student_id=(select private.frahoosh_current_student_id()));

drop policy if exists frahoosh_consumer_message_insert on public.messages;
create policy frahoosh_consumer_message_insert on public.messages
for insert to authenticated
with check (
  (select private.frahoosh_current_role()) in ('student','parent','دانش‌آموز','ولی','اولیا')
  and (
    sender_user_id=auth.uid()
    or lower(coalesce(sender,''))=lower(coalesce(auth.jwt()->>'email',''))
    or exists (
      select 1 from public.account_settings a
      where lower(coalesce(a.email,''))=lower(coalesce(auth.jwt()->>'email',''))
        and lower(coalesce(sender,'')) in
            (lower(coalesce(a.username,'')),lower(coalesce(a.national_code,'')))
    )
  )
);

drop policy if exists frahoosh_parent_payment_insert on public.payment_attempts;
create policy frahoosh_parent_payment_insert on public.payment_attempts
for insert to authenticated
with check (
  (select private.frahoosh_current_role()) in ('parent','ولی','اولیا')
  and (
    lower(coalesce(payer_username,''))=lower(coalesce(auth.jwt()->>'email',''))
    or exists (
      select 1 from public.account_settings a
      where lower(coalesce(a.email,''))=lower(coalesce(auth.jwt()->>'email',''))
        and lower(coalesce(payer_username,''))=lower(coalesce(a.username,''))
    )
  )
  and exists (
    select 1
    from public.parent_children pc
    join public.account_settings a
      on lower(coalesce(pc.parent_username,'')) in
         (lower(coalesce(a.username,'')),lower(coalesce(a.email,'')))
    where pc.student_id=payment_attempts.student_id
      and lower(coalesce(a.email,''))=lower(coalesce(auth.jwt()->>'email',''))
  )
);
