-- Make bigint primary keys generated automatically across the canonical public schema.
-- Existing ids are preserved; sequences are advanced to max(id)+1.
do $$
declare
  r record;
  seq text;
  next_id bigint;
begin
  for r in
    select n.nspname as schema_name, c.relname as table_name
    from pg_class c
    join pg_namespace n on n.oid=c.relnamespace
    join pg_attribute a on a.attrelid=c.oid and a.attname='id'
    where n.nspname='public'
      and c.relkind='r'
      and a.atttypid='int8'::regtype
      and a.attidentity=''
      and a.attgenerated=''
  loop
    execute format('alter table %I.%I alter column id add generated by default as identity', r.schema_name, r.table_name);
    seq := pg_get_serial_sequence(format('%I.%I', r.schema_name, r.table_name), 'id');
    execute format('select coalesce(max(id),0)+1 from %I.%I', r.schema_name, r.table_name) into next_id;
    if seq is not null then
      perform setval(seq, next_id, false);
    end if;
  end loop;
end $$;
