-- Frahoosh ZIP contract: final missing table + cross-panel student/parent data links.
-- Idempotent. Web and Android consume the same canonical records.

create table if not exists public.school_class_config (
  id bigint generated by default as identity primary key,
  grade text,
  class_name text,
  teacher_id bigint,
  capacity integer default 0,
  academic_year text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.online_class_chat (
  id bigint generated by default as identity primary key,
  class_id bigint,
  sender_id bigint,
  sender_role text,
  sender_name text,
  recipient_student_id bigint,
  is_private boolean not null default false,
  message text not null,
  sent_at_shamsi text,
  created_at timestamptz not null default now()
);

alter table public.online_class_chat enable row level security;
drop policy if exists online_class_chat_authenticated on public.online_class_chat;
create policy online_class_chat_authenticated
  on public.online_class_chat for all to authenticated
  using (true) with check (true);

alter table public.school_class_config enable row level security;

drop policy if exists school_class_config_manager on public.school_class_config;
create policy school_class_config_manager
  on public.school_class_config for all to authenticated
  using ((select private.frahoosh_current_role()) = any(array['مدیر','مدیریت','manager','معاون اجرایی','executive']))
  with check ((select private.frahoosh_current_role()) = any(array['مدیر','مدیریت','manager','معاون اجرایی','executive']));

drop policy if exists school_class_config_staff_read on public.school_class_config;
create policy school_class_config_staff_read
  on public.school_class_config for select to authenticated
  using ((select private.frahoosh_is_staff()));

-- Parent access follows the canonical parent_children relationship.
drop policy if exists parent_student_grades_read on public.student_grades;
create policy parent_student_grades_read
  on public.student_grades for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = student_grades.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_grades_read on public.grades;
create policy parent_grades_read
  on public.grades for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = grades.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_attendance_read on public.attendance;
create policy parent_attendance_read
  on public.attendance for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = attendance.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_assignments_read on public.assignments;
create policy parent_assignments_read
  on public.assignments for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = assignments.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_discipline_read on public.discipline_records;
create policy parent_discipline_read
  on public.discipline_records for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = discipline_records.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_report_cards_read on public.report_cards;
create policy parent_report_cards_read
  on public.report_cards for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = report_cards.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_monthly_report_cards_read on public.monthly_report_cards;
create policy parent_monthly_report_cards_read
  on public.monthly_report_cards for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = monthly_report_cards.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_payment_records_read on public.payment_records;
create policy parent_payment_records_read
  on public.payment_records for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = payment_records.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_assignment_submissions_read on public.assignment_submissions;
create policy parent_assignment_submissions_read
  on public.assignment_submissions for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = assignment_submissions.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_student_class_info_read on public.student_class_info;
create policy parent_student_class_info_read
  on public.student_class_info for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = student_class_info.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_class_seat_read on public.class_seat_assignments;
create policy parent_class_seat_read
  on public.class_seat_assignments for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = class_seat_assignments.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_exam_seat_read on public.exam_seat_assignments;
create policy parent_exam_seat_read
  on public.exam_seat_assignments for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = exam_seat_assignments.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_activity_registrations_read on public.activity_registrations;
create policy parent_activity_registrations_read
  on public.activity_registrations for select to authenticated
  using (
    exists (
      select 1 from public.parent_children pc
      where pc.student_id = activity_registrations.student_id
        and lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

drop policy if exists parent_transport_requests_read on public.transport_requests;
create policy parent_transport_requests_read
  on public.transport_requests for select to authenticated
  using (
    lower(coalesce(parent_username,'')) = lower(coalesce(auth.jwt()->>'email',''))
  );

drop policy if exists parent_activities_read on public.parent_activities;
create policy parent_activities_read
  on public.parent_activities for select to authenticated
  using (
    (select private.frahoosh_is_staff())
    or exists (
      select 1 from public.parent_children pc
      where lower(pc.parent_username) = lower(coalesce(auth.jwt()->>'email',''))
    )
  );

-- Student self-access mirrors the same canonical tables used by the Web flow.
drop policy if exists student_report_cards_read on public.report_cards;
create policy student_report_cards_read
  on public.report_cards for select to authenticated
  using (student_id = (select private.frahoosh_current_student_id()));

drop policy if exists student_monthly_report_cards_read on public.monthly_report_cards;
create policy student_monthly_report_cards_read
  on public.monthly_report_cards for select to authenticated
  using (student_id = (select private.frahoosh_current_student_id()));

drop policy if exists student_activity_registrations_read on public.activity_registrations;
create policy student_activity_registrations_read
  on public.activity_registrations for select to authenticated
  using (student_id = (select private.frahoosh_current_student_id()));

drop policy if exists student_assignment_submissions_read on public.assignment_submissions;
create policy student_assignment_submissions_read
  on public.assignment_submissions for select to authenticated
  using (student_id = (select private.frahoosh_current_student_id()));

drop policy if exists student_student_class_info_read on public.student_class_info;
create policy student_student_class_info_read
  on public.student_class_info for select to authenticated
  using (student_id = (select private.frahoosh_current_student_id()));

drop policy if exists student_class_seat_read on public.class_seat_assignments;
create policy student_class_seat_read
  on public.class_seat_assignments for select to authenticated
  using (student_id = (select private.frahoosh_current_student_id()));

drop policy if exists student_exam_seat_read on public.exam_seat_assignments;
create policy student_exam_seat_read
  on public.exam_seat_assignments for select to authenticated
  using (student_id = (select private.frahoosh_current_student_id()));
