-- Frahoosh: accounting invoice fields and student/parent identity confirmation workflow.
-- Idempotent and safe for existing installations.

alter table if exists public.finance_transactions
  add column if not exists invoice_number text,
  add column if not exists debit numeric default 0,
  add column if not exists credit numeric default 0,
  add column if not exists counterparty text;

create table if not exists public.identity_confirmations (
  id bigint generated by default as identity primary key,
  auth_user_id uuid,
  username text,
  role text not null,
  student_id bigint not null,
  confirmation_status text not null default 'confirmed',
  confirmed_at timestamptz not null default now(),
  note text
);

create index if not exists idx_identity_confirmations_student
  on public.identity_confirmations(student_id, confirmed_at desc);

alter table public.identity_confirmations enable row level security;

drop policy if exists identity_confirmation_insert on public.identity_confirmations;
create policy identity_confirmation_insert
  on public.identity_confirmations
  for insert to authenticated
  with check (true);

drop policy if exists identity_confirmation_owner_read on public.identity_confirmations;
create policy identity_confirmation_owner_read
  on public.identity_confirmations
  for select to authenticated
  using (
    lower(coalesce(username,'')) = lower(coalesce(auth.jwt()->>'email',''))
    or (select private.frahoosh_is_staff())
  );

drop policy if exists finance_transactions_authenticated on public.finance_transactions;
create policy finance_transactions_authenticated
  on public.finance_transactions
  for all to authenticated
  using ((select private.frahoosh_is_staff()))
  with check ((select private.frahoosh_is_staff()));
