-- Frahoosh meeting workflow + manager smart-class monitor.
-- Safe/idempotent migration for the existing Supabase schema.

create table if not exists public.meeting_requests (
  id bigint generated by default as identity primary key,
  school_id text,
  requester_user_id text,
  requester_role text not null,
  requester_name text,
  parent_id bigint,
  parent_name text,
  student_id bigint,
  student_name text,
  target_role text not null,
  target_user_id text,
  target_name text,
  requested_date_shamsi text not null,
  requested_time text not null,
  reason text not null,
  description text,
  manager_status text not null default 'در انتظار تایید مدیر',
  manager_note text,
  manager_approved_by text,
  manager_approved_at timestamptz,
  educational_status text not null default 'در انتظار ارجاع معاون آموزشی',
  educational_note text,
  final_date_shamsi text,
  final_time text,
  final_status text not null default 'در انتظار بررسی',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_meeting_requests_student on public.meeting_requests(student_id);
create index if not exists idx_meeting_requests_requester on public.meeting_requests(requester_user_id);
create index if not exists idx_meeting_requests_target on public.meeting_requests(target_user_id);
create index if not exists idx_meeting_requests_status on public.meeting_requests(manager_status, educational_status, final_status);

alter table public.meeting_requests enable row level security;

drop policy if exists "meeting manager all" on public.meeting_requests;
drop policy if exists "meeting staff read" on public.meeting_requests;
drop policy if exists "meeting requester read" on public.meeting_requests;
drop policy if exists "meeting parent insert" on public.meeting_requests;

create policy "meeting manager all" on public.meeting_requests
for all to authenticated
using ((select private.frahoosh_current_role()) = any(array['مدیر','مدیریت','manager']))
with check ((select private.frahoosh_current_role()) = any(array['مدیر','مدیریت','manager']));

create policy "meeting staff read" on public.meeting_requests
for select to authenticated
using ((select private.frahoosh_is_staff()));

create policy "meeting requester read" on public.meeting_requests
for select to authenticated
using (
  lower(coalesce(requester_user_id,'')) = lower(coalesce(auth.jwt()->>'email',''))
  or lower(coalesce(requester_user_id,'')) = lower(coalesce(auth.uid()::text,''))
);

create policy "meeting parent insert" on public.meeting_requests
for insert to authenticated
with check (
  requester_role in ('parent','اولیا')
  and (
    lower(coalesce(requester_user_id,'')) = lower(coalesce(auth.jwt()->>'email',''))
    or lower(coalesce(requester_user_id,'')) = lower(coalesce(auth.uid()::text,''))
  )
);

create or replace function public.frahoosh_update_meeting_request(
  p_id bigint,
  p_action text,
  p_note text default null,
  p_final_date text default null,
  p_final_time text default null
)
returns public.meeting_requests
language plpgsql
security invoker
as $$
declare r public.meeting_requests;
begin
  select * into r from public.meeting_requests where id=p_id for update;
  if not found then raise exception 'درخواست ملاقات پیدا نشد'; end if;

  if lower(coalesce((select private.frahoosh_current_role()),'')) = any(array['مدیر','مدیریت','manager']) then
    if p_action='approve' then
      update public.meeting_requests set manager_status='تایید مدیر', manager_note=p_note,
        manager_approved_by=coalesce(auth.jwt()->>'email',auth.uid()::text), manager_approved_at=now(),
        educational_status='ارجاع شده به معاون آموزشی', final_status='ارجاع شده به معاون آموزشی',
        updated_at=now() where id=p_id returning * into r;
    elsif p_action='reject' then
      update public.meeting_requests set manager_status='رد مدیر', manager_note=p_note,
        final_status='رد شده', updated_at=now() where id=p_id returning * into r;
    else
      raise exception 'عملیات مدیر نامعتبر است';
    end if;
  elsif lower(coalesce((select private.frahoosh_current_role()),'')) = any(array['معاون آموزشی','educational']) then
    if p_action='schedule' then
      update public.meeting_requests set educational_status='تایید معاون آموزشی',
        educational_note=p_note, final_date_shamsi=coalesce(p_final_date,requested_date_shamsi),
        final_time=coalesce(p_final_time,requested_time), final_status='تایید نهایی',
        updated_at=now() where id=p_id
      and manager_status='تایید مدیر' returning * into r;
      if not found then raise exception 'درخواست باید ابتدا توسط مدیر تایید شده باشد'; end if;
    elsif p_action='reject' then
      update public.meeting_requests set educational_status='رد معاون آموزشی',
        educational_note=p_note, final_status='رد شده', updated_at=now() where id=p_id
      and manager_status='تایید مدیر' returning * into r;
      if not found then raise exception 'درخواست باید ابتدا توسط مدیر تایید شده باشد'; end if;
    else
      raise exception 'عملیات معاون آموزشی نامعتبر است';
    end if;
  else
    raise exception 'شما مجوز تغییر این درخواست را ندارید';
  end if;
  return r;
end $$;

revoke all on function public.frahoosh_update_meeting_request(bigint,text,text,text,text) from public;
grant execute on function public.frahoosh_update_meeting_request(bigint,text,text,text,text) to authenticated;
