-- Frahoosh meeting workflow: parent/teacher/staff/counselor meetings.
-- Requests require manager approval and are then routed to the educational deputy.
create table if not exists public.meeting_requests (
  id bigint generated by default as identity primary key,
  requester_username text not null,
  requester_role text not null,
  requester_name text,
  student_id bigint,
  student_name text,
  parent_username text,
  parent_name text,
  target_role text not null,
  target_user_id bigint,
  target_username text,
  target_name text,
  requested_date text not null,
  requested_time text not null,
  reason text not null,
  description text,
  status text not null default 'pending_manager',
  manager_status text not null default 'pending',
  manager_note text,
  manager_approved_at timestamptz,
  educational_status text not null default 'pending',
  educational_note text,
  final_date text,
  final_time text,
  final_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_meeting_requests_requester on public.meeting_requests(requester_username);
create index if not exists idx_meeting_requests_target on public.meeting_requests(target_username);
create index if not exists idx_meeting_requests_student on public.meeting_requests(student_id);
create index if not exists idx_meeting_requests_status on public.meeting_requests(status);

alter table public.meeting_requests enable row level security;

drop policy if exists "meeting manager full access" on public.meeting_requests;
create policy "meeting manager full access" on public.meeting_requests
for all to authenticated
using ((select private.frahoosh_current_role()) = any(array['مدیر','مدیریت','manager','admin']))
with check ((select private.frahoosh_current_role()) = any(array['مدیر','مدیریت','manager','admin']));

drop policy if exists "meeting requester read" on public.meeting_requests;
create policy "meeting requester read" on public.meeting_requests
for select to authenticated
using (lower(requester_username)=lower(coalesce(auth.jwt()->>'email','')));

drop policy if exists "meeting target read" on public.meeting_requests;
create policy "meeting target read" on public.meeting_requests
for select to authenticated
using (lower(target_username)=lower(coalesce(auth.jwt()->>'email','')));

drop policy if exists "meeting parent insert" on public.meeting_requests;
create policy "meeting parent insert" on public.meeting_requests
for insert to authenticated
with check (
  lower(requester_username)=lower(coalesce(auth.jwt()->>'email',''))
  and requester_role=any(array['parent','اولیا'])
);

drop policy if exists "meeting teacher staff insert" on public.meeting_requests;
create policy "meeting teacher staff insert" on public.meeting_requests
for insert to authenticated
with check (
  lower(requester_username)=lower(coalesce(auth.jwt()->>'email',''))
  and requester_role=any(array['teacher','دبیر','staff','کادر','counselor','مشاور'])
);

drop policy if exists "meeting educational review" on public.meeting_requests;
create policy "meeting educational review" on public.meeting_requests
for select to authenticated
using ((select private.frahoosh_current_role()) = any(array['معاون آموزشی','educational','manager','مدیر','مدیریت']));

drop policy if exists "meeting educational update" on public.meeting_requests;
create policy "meeting educational update" on public.meeting_requests
for update to authenticated
using ((select private.frahoosh_current_role()) = any(array['معاون آموزشی','educational','manager','مدیر','مدیریت']))
with check ((select private.frahoosh_current_role()) = any(array['معاون آموزشی','educational','manager','مدیر','مدیریت']));

create or replace function public.frahoosh_meeting_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_meeting_requests_updated_at on public.meeting_requests;
create trigger trg_meeting_requests_updated_at
before update on public.meeting_requests
for each row execute function public.frahoosh_meeting_touch_updated_at();
