-- Operational backing tables for the complete canonical Frahoosh module catalog.
CREATE TABLE IF NOT EXISTS public."academic_followups" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "student_name" text,
  "class_name" text,
  "subject" text,
  "date_shamsi" text,
  "followup_item" text,
  "decision" text,
  "note" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."academic_followups" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."academic_followups" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."academic_followups_id_seq" TO authenticated;
DROP POLICY IF EXISTS "academic_followups_select_frahoosh" ON public."academic_followups";
CREATE POLICY "academic_followups_select_frahoosh" ON public."academic_followups" FOR SELECT TO authenticated USING (private.frahoosh_can_access('academic_followups', to_jsonb("academic_followups"), 'select'));
DROP POLICY IF EXISTS "academic_followups_insert_frahoosh" ON public."academic_followups";
CREATE POLICY "academic_followups_insert_frahoosh" ON public."academic_followups" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('academic_followups', to_jsonb("academic_followups"), 'insert'));
DROP POLICY IF EXISTS "academic_followups_update_frahoosh" ON public."academic_followups";
CREATE POLICY "academic_followups_update_frahoosh" ON public."academic_followups" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('academic_followups', to_jsonb("academic_followups"), 'update')) WITH CHECK (private.frahoosh_can_access('academic_followups', to_jsonb("academic_followups"), 'update'));
DROP POLICY IF EXISTS "academic_followups_delete_frahoosh" ON public."academic_followups";
CREATE POLICY "academic_followups_delete_frahoosh" ON public."academic_followups" FOR DELETE TO authenticated USING (private.frahoosh_can_access('academic_followups', to_jsonb("academic_followups"), 'delete'));
CREATE INDEX IF NOT EXISTS "academic_followups_student_id_idx" ON public."academic_followups" (student_id);
CREATE TABLE IF NOT EXISTS public."activity_programs" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "activity_key" text,
  "title" text,
  "category" text,
  "active" boolean NOT NULL DEFAULT false,
  "amount" numeric,
  "settings" jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."activity_programs" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."activity_programs" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."activity_programs_id_seq" TO authenticated;
DROP POLICY IF EXISTS "activity_programs_select_frahoosh" ON public."activity_programs";
CREATE POLICY "activity_programs_select_frahoosh" ON public."activity_programs" FOR SELECT TO authenticated USING (private.frahoosh_can_access('activity_programs', to_jsonb("activity_programs"), 'select'));
DROP POLICY IF EXISTS "activity_programs_insert_frahoosh" ON public."activity_programs";
CREATE POLICY "activity_programs_insert_frahoosh" ON public."activity_programs" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('activity_programs', to_jsonb("activity_programs"), 'insert'));
DROP POLICY IF EXISTS "activity_programs_update_frahoosh" ON public."activity_programs";
CREATE POLICY "activity_programs_update_frahoosh" ON public."activity_programs" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('activity_programs', to_jsonb("activity_programs"), 'update')) WITH CHECK (private.frahoosh_can_access('activity_programs', to_jsonb("activity_programs"), 'update'));
DROP POLICY IF EXISTS "activity_programs_delete_frahoosh" ON public."activity_programs";
CREATE POLICY "activity_programs_delete_frahoosh" ON public."activity_programs" FOR DELETE TO authenticated USING (private.frahoosh_can_access('activity_programs', to_jsonb("activity_programs"), 'delete'));
CREATE TABLE IF NOT EXISTS public."activity_registrations" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "activity_id" bigint,
  "student_id" bigint,
  "participation_type" text,
  "team_members" text,
  "competition_type" text,
  "payment_status" text,
  "status" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."activity_registrations" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."activity_registrations" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."activity_registrations_id_seq" TO authenticated;
DROP POLICY IF EXISTS "activity_registrations_select_frahoosh" ON public."activity_registrations";
CREATE POLICY "activity_registrations_select_frahoosh" ON public."activity_registrations" FOR SELECT TO authenticated USING (private.frahoosh_can_access('activity_registrations', to_jsonb("activity_registrations"), 'select'));
DROP POLICY IF EXISTS "activity_registrations_insert_frahoosh" ON public."activity_registrations";
CREATE POLICY "activity_registrations_insert_frahoosh" ON public."activity_registrations" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('activity_registrations', to_jsonb("activity_registrations"), 'insert'));
DROP POLICY IF EXISTS "activity_registrations_update_frahoosh" ON public."activity_registrations";
CREATE POLICY "activity_registrations_update_frahoosh" ON public."activity_registrations" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('activity_registrations', to_jsonb("activity_registrations"), 'update')) WITH CHECK (private.frahoosh_can_access('activity_registrations', to_jsonb("activity_registrations"), 'update'));
DROP POLICY IF EXISTS "activity_registrations_delete_frahoosh" ON public."activity_registrations";
CREATE POLICY "activity_registrations_delete_frahoosh" ON public."activity_registrations" FOR DELETE TO authenticated USING (private.frahoosh_can_access('activity_registrations', to_jsonb("activity_registrations"), 'delete'));
CREATE INDEX IF NOT EXISTS "activity_registrations_student_id_idx" ON public."activity_registrations" (student_id);
CREATE TABLE IF NOT EXISTS public."ai_assistant_sessions" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" text,
  "role" text,
  "title" text,
  "request_date_shamsi" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."ai_assistant_sessions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."ai_assistant_sessions" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."ai_assistant_sessions_id_seq" TO authenticated;
DROP POLICY IF EXISTS "ai_assistant_sessions_select_frahoosh" ON public."ai_assistant_sessions";
CREATE POLICY "ai_assistant_sessions_select_frahoosh" ON public."ai_assistant_sessions" FOR SELECT TO authenticated USING (private.frahoosh_can_access('ai_assistant_sessions', to_jsonb("ai_assistant_sessions"), 'select'));
DROP POLICY IF EXISTS "ai_assistant_sessions_insert_frahoosh" ON public."ai_assistant_sessions";
CREATE POLICY "ai_assistant_sessions_insert_frahoosh" ON public."ai_assistant_sessions" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('ai_assistant_sessions', to_jsonb("ai_assistant_sessions"), 'insert'));
DROP POLICY IF EXISTS "ai_assistant_sessions_update_frahoosh" ON public."ai_assistant_sessions";
CREATE POLICY "ai_assistant_sessions_update_frahoosh" ON public."ai_assistant_sessions" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('ai_assistant_sessions', to_jsonb("ai_assistant_sessions"), 'update')) WITH CHECK (private.frahoosh_can_access('ai_assistant_sessions', to_jsonb("ai_assistant_sessions"), 'update'));
DROP POLICY IF EXISTS "ai_assistant_sessions_delete_frahoosh" ON public."ai_assistant_sessions";
CREATE POLICY "ai_assistant_sessions_delete_frahoosh" ON public."ai_assistant_sessions" FOR DELETE TO authenticated USING (private.frahoosh_can_access('ai_assistant_sessions', to_jsonb("ai_assistant_sessions"), 'delete'));
CREATE TABLE IF NOT EXISTS public."ai_questions" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" text,
  "role" text,
  "question" text,
  "answer" text,
  "answer_date_shamsi" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."ai_questions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."ai_questions" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."ai_questions_id_seq" TO authenticated;
DROP POLICY IF EXISTS "ai_questions_select_frahoosh" ON public."ai_questions";
CREATE POLICY "ai_questions_select_frahoosh" ON public."ai_questions" FOR SELECT TO authenticated USING (private.frahoosh_can_access('ai_questions', to_jsonb("ai_questions"), 'select'));
DROP POLICY IF EXISTS "ai_questions_insert_frahoosh" ON public."ai_questions";
CREATE POLICY "ai_questions_insert_frahoosh" ON public."ai_questions" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('ai_questions', to_jsonb("ai_questions"), 'insert'));
DROP POLICY IF EXISTS "ai_questions_update_frahoosh" ON public."ai_questions";
CREATE POLICY "ai_questions_update_frahoosh" ON public."ai_questions" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('ai_questions', to_jsonb("ai_questions"), 'update')) WITH CHECK (private.frahoosh_can_access('ai_questions', to_jsonb("ai_questions"), 'update'));
DROP POLICY IF EXISTS "ai_questions_delete_frahoosh" ON public."ai_questions";
CREATE POLICY "ai_questions_delete_frahoosh" ON public."ai_questions" FOR DELETE TO authenticated USING (private.frahoosh_can_access('ai_questions', to_jsonb("ai_questions"), 'delete'));
CREATE TABLE IF NOT EXISTS public."ai_smart_reports" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text,
  "report_type" text,
  "target_type" text,
  "target_id" text,
  "created_by" text,
  "report_date_shamsi" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."ai_smart_reports" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."ai_smart_reports" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."ai_smart_reports_id_seq" TO authenticated;
DROP POLICY IF EXISTS "ai_smart_reports_select_frahoosh" ON public."ai_smart_reports";
CREATE POLICY "ai_smart_reports_select_frahoosh" ON public."ai_smart_reports" FOR SELECT TO authenticated USING (private.frahoosh_can_access('ai_smart_reports', to_jsonb("ai_smart_reports"), 'select'));
DROP POLICY IF EXISTS "ai_smart_reports_insert_frahoosh" ON public."ai_smart_reports";
CREATE POLICY "ai_smart_reports_insert_frahoosh" ON public."ai_smart_reports" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('ai_smart_reports', to_jsonb("ai_smart_reports"), 'insert'));
DROP POLICY IF EXISTS "ai_smart_reports_update_frahoosh" ON public."ai_smart_reports";
CREATE POLICY "ai_smart_reports_update_frahoosh" ON public."ai_smart_reports" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('ai_smart_reports', to_jsonb("ai_smart_reports"), 'update')) WITH CHECK (private.frahoosh_can_access('ai_smart_reports', to_jsonb("ai_smart_reports"), 'update'));
DROP POLICY IF EXISTS "ai_smart_reports_delete_frahoosh" ON public."ai_smart_reports";
CREATE POLICY "ai_smart_reports_delete_frahoosh" ON public."ai_smart_reports" FOR DELETE TO authenticated USING (private.frahoosh_can_access('ai_smart_reports', to_jsonb("ai_smart_reports"), 'delete'));
CREATE TABLE IF NOT EXISTS public."assets" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text,
  "category" text,
  "quantity" integer,
  "location" text,
  "archived" boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."assets" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."assets" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."assets_id_seq" TO authenticated;
DROP POLICY IF EXISTS "assets_select_frahoosh" ON public."assets";
CREATE POLICY "assets_select_frahoosh" ON public."assets" FOR SELECT TO authenticated USING (private.frahoosh_can_access('assets', to_jsonb("assets"), 'select'));
DROP POLICY IF EXISTS "assets_insert_frahoosh" ON public."assets";
CREATE POLICY "assets_insert_frahoosh" ON public."assets" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('assets', to_jsonb("assets"), 'insert'));
DROP POLICY IF EXISTS "assets_update_frahoosh" ON public."assets";
CREATE POLICY "assets_update_frahoosh" ON public."assets" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('assets', to_jsonb("assets"), 'update')) WITH CHECK (private.frahoosh_can_access('assets', to_jsonb("assets"), 'update'));
DROP POLICY IF EXISTS "assets_delete_frahoosh" ON public."assets";
CREATE POLICY "assets_delete_frahoosh" ON public."assets" FOR DELETE TO authenticated USING (private.frahoosh_can_access('assets', to_jsonb("assets"), 'delete'));
CREATE TABLE IF NOT EXISTS public."backup_records" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text,
  "backup_path" text,
  "status" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."backup_records" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."backup_records" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."backup_records_id_seq" TO authenticated;
DROP POLICY IF EXISTS "backup_records_select_frahoosh" ON public."backup_records";
CREATE POLICY "backup_records_select_frahoosh" ON public."backup_records" FOR SELECT TO authenticated USING (private.frahoosh_can_access('backup_records', to_jsonb("backup_records"), 'select'));
DROP POLICY IF EXISTS "backup_records_insert_frahoosh" ON public."backup_records";
CREATE POLICY "backup_records_insert_frahoosh" ON public."backup_records" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('backup_records', to_jsonb("backup_records"), 'insert'));
DROP POLICY IF EXISTS "backup_records_update_frahoosh" ON public."backup_records";
CREATE POLICY "backup_records_update_frahoosh" ON public."backup_records" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('backup_records', to_jsonb("backup_records"), 'update')) WITH CHECK (private.frahoosh_can_access('backup_records', to_jsonb("backup_records"), 'update'));
DROP POLICY IF EXISTS "backup_records_delete_frahoosh" ON public."backup_records";
CREATE POLICY "backup_records_delete_frahoosh" ON public."backup_records" FOR DELETE TO authenticated USING (private.frahoosh_can_access('backup_records', to_jsonb("backup_records"), 'delete'));
CREATE TABLE IF NOT EXISTS public."certificate_requests" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "student_name" text,
  "destination" text,
  "request_date" text,
  "status" text,
  "executive_note" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."certificate_requests" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."certificate_requests" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."certificate_requests_id_seq" TO authenticated;
DROP POLICY IF EXISTS "certificate_requests_select_frahoosh" ON public."certificate_requests";
CREATE POLICY "certificate_requests_select_frahoosh" ON public."certificate_requests" FOR SELECT TO authenticated USING (private.frahoosh_can_access('certificate_requests', to_jsonb("certificate_requests"), 'select'));
DROP POLICY IF EXISTS "certificate_requests_insert_frahoosh" ON public."certificate_requests";
CREATE POLICY "certificate_requests_insert_frahoosh" ON public."certificate_requests" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('certificate_requests', to_jsonb("certificate_requests"), 'insert'));
DROP POLICY IF EXISTS "certificate_requests_update_frahoosh" ON public."certificate_requests";
CREATE POLICY "certificate_requests_update_frahoosh" ON public."certificate_requests" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('certificate_requests', to_jsonb("certificate_requests"), 'update')) WITH CHECK (private.frahoosh_can_access('certificate_requests', to_jsonb("certificate_requests"), 'update'));
DROP POLICY IF EXISTS "certificate_requests_delete_frahoosh" ON public."certificate_requests";
CREATE POLICY "certificate_requests_delete_frahoosh" ON public."certificate_requests" FOR DELETE TO authenticated USING (private.frahoosh_can_access('certificate_requests', to_jsonb("certificate_requests"), 'delete'));
CREATE INDEX IF NOT EXISTS "certificate_requests_student_id_idx" ON public."certificate_requests" (student_id);
CREATE TABLE IF NOT EXISTS public."certificates" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "title" text,
  "code" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."certificates" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."certificates" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."certificates_id_seq" TO authenticated;
DROP POLICY IF EXISTS "certificates_select_frahoosh" ON public."certificates";
CREATE POLICY "certificates_select_frahoosh" ON public."certificates" FOR SELECT TO authenticated USING (private.frahoosh_can_access('certificates', to_jsonb("certificates"), 'select'));
DROP POLICY IF EXISTS "certificates_insert_frahoosh" ON public."certificates";
CREATE POLICY "certificates_insert_frahoosh" ON public."certificates" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('certificates', to_jsonb("certificates"), 'insert'));
DROP POLICY IF EXISTS "certificates_update_frahoosh" ON public."certificates";
CREATE POLICY "certificates_update_frahoosh" ON public."certificates" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('certificates', to_jsonb("certificates"), 'update')) WITH CHECK (private.frahoosh_can_access('certificates', to_jsonb("certificates"), 'update'));
DROP POLICY IF EXISTS "certificates_delete_frahoosh" ON public."certificates";
CREATE POLICY "certificates_delete_frahoosh" ON public."certificates" FOR DELETE TO authenticated USING (private.frahoosh_can_access('certificates', to_jsonb("certificates"), 'delete'));
CREATE INDEX IF NOT EXISTS "certificates_student_id_idx" ON public."certificates" (student_id);
CREATE TABLE IF NOT EXISTS public."class_cards" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "class_name" text,
  "code" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."class_cards" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."class_cards" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."class_cards_id_seq" TO authenticated;
DROP POLICY IF EXISTS "class_cards_select_frahoosh" ON public."class_cards";
CREATE POLICY "class_cards_select_frahoosh" ON public."class_cards" FOR SELECT TO authenticated USING (private.frahoosh_can_access('class_cards', to_jsonb("class_cards"), 'select'));
DROP POLICY IF EXISTS "class_cards_insert_frahoosh" ON public."class_cards";
CREATE POLICY "class_cards_insert_frahoosh" ON public."class_cards" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('class_cards', to_jsonb("class_cards"), 'insert'));
DROP POLICY IF EXISTS "class_cards_update_frahoosh" ON public."class_cards";
CREATE POLICY "class_cards_update_frahoosh" ON public."class_cards" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('class_cards', to_jsonb("class_cards"), 'update')) WITH CHECK (private.frahoosh_can_access('class_cards', to_jsonb("class_cards"), 'update'));
DROP POLICY IF EXISTS "class_cards_delete_frahoosh" ON public."class_cards";
CREATE POLICY "class_cards_delete_frahoosh" ON public."class_cards" FOR DELETE TO authenticated USING (private.frahoosh_can_access('class_cards', to_jsonb("class_cards"), 'delete'));
CREATE INDEX IF NOT EXISTS "class_cards_student_id_idx" ON public."class_cards" (student_id);
CREATE TABLE IF NOT EXISTS public."class_seat_assignments" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" bigint,
  "student_id" bigint,
  "seat_number" integer,
  "academic_year" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."class_seat_assignments" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."class_seat_assignments" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."class_seat_assignments_id_seq" TO authenticated;
DROP POLICY IF EXISTS "class_seat_assignments_select_frahoosh" ON public."class_seat_assignments";
CREATE POLICY "class_seat_assignments_select_frahoosh" ON public."class_seat_assignments" FOR SELECT TO authenticated USING (private.frahoosh_can_access('class_seat_assignments', to_jsonb("class_seat_assignments"), 'select'));
DROP POLICY IF EXISTS "class_seat_assignments_insert_frahoosh" ON public."class_seat_assignments";
CREATE POLICY "class_seat_assignments_insert_frahoosh" ON public."class_seat_assignments" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('class_seat_assignments', to_jsonb("class_seat_assignments"), 'insert'));
DROP POLICY IF EXISTS "class_seat_assignments_update_frahoosh" ON public."class_seat_assignments";
CREATE POLICY "class_seat_assignments_update_frahoosh" ON public."class_seat_assignments" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('class_seat_assignments', to_jsonb("class_seat_assignments"), 'update')) WITH CHECK (private.frahoosh_can_access('class_seat_assignments', to_jsonb("class_seat_assignments"), 'update'));
DROP POLICY IF EXISTS "class_seat_assignments_delete_frahoosh" ON public."class_seat_assignments";
CREATE POLICY "class_seat_assignments_delete_frahoosh" ON public."class_seat_assignments" FOR DELETE TO authenticated USING (private.frahoosh_can_access('class_seat_assignments', to_jsonb("class_seat_assignments"), 'delete'));
CREATE INDEX IF NOT EXISTS "class_seat_assignments_student_id_idx" ON public."class_seat_assignments" (student_id);
CREATE TABLE IF NOT EXISTS public."competitions" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text,
  "category" text,
  "start_date" text,
  "end_date" text,
  "status" text,
  "description" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."competitions" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."competitions" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."competitions_id_seq" TO authenticated;
DROP POLICY IF EXISTS "competitions_select_frahoosh" ON public."competitions";
CREATE POLICY "competitions_select_frahoosh" ON public."competitions" FOR SELECT TO authenticated USING (private.frahoosh_can_access('competitions', to_jsonb("competitions"), 'select'));
DROP POLICY IF EXISTS "competitions_insert_frahoosh" ON public."competitions";
CREATE POLICY "competitions_insert_frahoosh" ON public."competitions" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('competitions', to_jsonb("competitions"), 'insert'));
DROP POLICY IF EXISTS "competitions_update_frahoosh" ON public."competitions";
CREATE POLICY "competitions_update_frahoosh" ON public."competitions" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('competitions', to_jsonb("competitions"), 'update')) WITH CHECK (private.frahoosh_can_access('competitions', to_jsonb("competitions"), 'update'));
DROP POLICY IF EXISTS "competitions_delete_frahoosh" ON public."competitions";
CREATE POLICY "competitions_delete_frahoosh" ON public."competitions" FOR DELETE TO authenticated USING (private.frahoosh_can_access('competitions', to_jsonb("competitions"), 'delete'));
CREATE TABLE IF NOT EXISTS public."educational_activities" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text,
  "subject" text,
  "grade" text,
  "class_name" text,
  "teacher_id" bigint,
  "student_id" bigint,
  "activity_date" text,
  "description" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."educational_activities" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."educational_activities" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."educational_activities_id_seq" TO authenticated;
DROP POLICY IF EXISTS "educational_activities_select_frahoosh" ON public."educational_activities";
CREATE POLICY "educational_activities_select_frahoosh" ON public."educational_activities" FOR SELECT TO authenticated USING (private.frahoosh_can_access('educational_activities', to_jsonb("educational_activities"), 'select'));
DROP POLICY IF EXISTS "educational_activities_insert_frahoosh" ON public."educational_activities";
CREATE POLICY "educational_activities_insert_frahoosh" ON public."educational_activities" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('educational_activities', to_jsonb("educational_activities"), 'insert'));
DROP POLICY IF EXISTS "educational_activities_update_frahoosh" ON public."educational_activities";
CREATE POLICY "educational_activities_update_frahoosh" ON public."educational_activities" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('educational_activities', to_jsonb("educational_activities"), 'update')) WITH CHECK (private.frahoosh_can_access('educational_activities', to_jsonb("educational_activities"), 'update'));
DROP POLICY IF EXISTS "educational_activities_delete_frahoosh" ON public."educational_activities";
CREATE POLICY "educational_activities_delete_frahoosh" ON public."educational_activities" FOR DELETE TO authenticated USING (private.frahoosh_can_access('educational_activities', to_jsonb("educational_activities"), 'delete'));
CREATE INDEX IF NOT EXISTS "educational_activities_student_id_idx" ON public."educational_activities" (student_id);
CREATE INDEX IF NOT EXISTS "educational_activities_teacher_id_idx" ON public."educational_activities" (teacher_id);
CREATE TABLE IF NOT EXISTS public."educational_followups" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "student_name" text,
  "class_name" text,
  "date_shamsi" text,
  "followup_item" text,
  "decision" text,
  "note" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."educational_followups" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."educational_followups" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."educational_followups_id_seq" TO authenticated;
DROP POLICY IF EXISTS "educational_followups_select_frahoosh" ON public."educational_followups";
CREATE POLICY "educational_followups_select_frahoosh" ON public."educational_followups" FOR SELECT TO authenticated USING (private.frahoosh_can_access('educational_followups', to_jsonb("educational_followups"), 'select'));
DROP POLICY IF EXISTS "educational_followups_insert_frahoosh" ON public."educational_followups";
CREATE POLICY "educational_followups_insert_frahoosh" ON public."educational_followups" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('educational_followups', to_jsonb("educational_followups"), 'insert'));
DROP POLICY IF EXISTS "educational_followups_update_frahoosh" ON public."educational_followups";
CREATE POLICY "educational_followups_update_frahoosh" ON public."educational_followups" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('educational_followups', to_jsonb("educational_followups"), 'update')) WITH CHECK (private.frahoosh_can_access('educational_followups', to_jsonb("educational_followups"), 'update'));
DROP POLICY IF EXISTS "educational_followups_delete_frahoosh" ON public."educational_followups";
CREATE POLICY "educational_followups_delete_frahoosh" ON public."educational_followups" FOR DELETE TO authenticated USING (private.frahoosh_can_access('educational_followups', to_jsonb("educational_followups"), 'delete'));
CREATE INDEX IF NOT EXISTS "educational_followups_student_id_idx" ON public."educational_followups" (student_id);
CREATE TABLE IF NOT EXISTS public."exam_seat_assignments" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exam_id" bigint,
  "student_id" bigint,
  "subject" text,
  "exam_date" text,
  "seat_number" integer,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."exam_seat_assignments" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."exam_seat_assignments" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."exam_seat_assignments_id_seq" TO authenticated;
DROP POLICY IF EXISTS "exam_seat_assignments_select_frahoosh" ON public."exam_seat_assignments";
CREATE POLICY "exam_seat_assignments_select_frahoosh" ON public."exam_seat_assignments" FOR SELECT TO authenticated USING (private.frahoosh_can_access('exam_seat_assignments', to_jsonb("exam_seat_assignments"), 'select'));
DROP POLICY IF EXISTS "exam_seat_assignments_insert_frahoosh" ON public."exam_seat_assignments";
CREATE POLICY "exam_seat_assignments_insert_frahoosh" ON public."exam_seat_assignments" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('exam_seat_assignments', to_jsonb("exam_seat_assignments"), 'insert'));
DROP POLICY IF EXISTS "exam_seat_assignments_update_frahoosh" ON public."exam_seat_assignments";
CREATE POLICY "exam_seat_assignments_update_frahoosh" ON public."exam_seat_assignments" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('exam_seat_assignments', to_jsonb("exam_seat_assignments"), 'update')) WITH CHECK (private.frahoosh_can_access('exam_seat_assignments', to_jsonb("exam_seat_assignments"), 'update'));
DROP POLICY IF EXISTS "exam_seat_assignments_delete_frahoosh" ON public."exam_seat_assignments";
CREATE POLICY "exam_seat_assignments_delete_frahoosh" ON public."exam_seat_assignments" FOR DELETE TO authenticated USING (private.frahoosh_can_access('exam_seat_assignments', to_jsonb("exam_seat_assignments"), 'delete'));
CREATE INDEX IF NOT EXISTS "exam_seat_assignments_student_id_idx" ON public."exam_seat_assignments" (student_id);
CREATE TABLE IF NOT EXISTS public."grade_items" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "teacher_id" bigint,
  "subject" text,
  "grade_type" text,
  "term" text,
  "score" numeric,
  "grade_date" text,
  "description" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."grade_items" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."grade_items" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."grade_items_id_seq" TO authenticated;
DROP POLICY IF EXISTS "grade_items_select_frahoosh" ON public."grade_items";
CREATE POLICY "grade_items_select_frahoosh" ON public."grade_items" FOR SELECT TO authenticated USING (private.frahoosh_can_access('grade_items', to_jsonb("grade_items"), 'select'));
DROP POLICY IF EXISTS "grade_items_insert_frahoosh" ON public."grade_items";
CREATE POLICY "grade_items_insert_frahoosh" ON public."grade_items" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('grade_items', to_jsonb("grade_items"), 'insert'));
DROP POLICY IF EXISTS "grade_items_update_frahoosh" ON public."grade_items";
CREATE POLICY "grade_items_update_frahoosh" ON public."grade_items" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('grade_items', to_jsonb("grade_items"), 'update')) WITH CHECK (private.frahoosh_can_access('grade_items', to_jsonb("grade_items"), 'update'));
DROP POLICY IF EXISTS "grade_items_delete_frahoosh" ON public."grade_items";
CREATE POLICY "grade_items_delete_frahoosh" ON public."grade_items" FOR DELETE TO authenticated USING (private.frahoosh_can_access('grade_items', to_jsonb("grade_items"), 'delete'));
CREATE INDEX IF NOT EXISTS "grade_items_student_id_idx" ON public."grade_items" (student_id);
CREATE INDEX IF NOT EXISTS "grade_items_teacher_id_idx" ON public."grade_items" (teacher_id);
CREATE TABLE IF NOT EXISTS public."khwarizmi_registrations" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text,
  "category" text,
  "grade" text,
  "class_name" text,
  "student_id" bigint,
  "status" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."khwarizmi_registrations" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."khwarizmi_registrations" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."khwarizmi_registrations_id_seq" TO authenticated;
DROP POLICY IF EXISTS "khwarizmi_registrations_select_frahoosh" ON public."khwarizmi_registrations";
CREATE POLICY "khwarizmi_registrations_select_frahoosh" ON public."khwarizmi_registrations" FOR SELECT TO authenticated USING (private.frahoosh_can_access('khwarizmi_registrations', to_jsonb("khwarizmi_registrations"), 'select'));
DROP POLICY IF EXISTS "khwarizmi_registrations_insert_frahoosh" ON public."khwarizmi_registrations";
CREATE POLICY "khwarizmi_registrations_insert_frahoosh" ON public."khwarizmi_registrations" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('khwarizmi_registrations', to_jsonb("khwarizmi_registrations"), 'insert'));
DROP POLICY IF EXISTS "khwarizmi_registrations_update_frahoosh" ON public."khwarizmi_registrations";
CREATE POLICY "khwarizmi_registrations_update_frahoosh" ON public."khwarizmi_registrations" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('khwarizmi_registrations', to_jsonb("khwarizmi_registrations"), 'update')) WITH CHECK (private.frahoosh_can_access('khwarizmi_registrations', to_jsonb("khwarizmi_registrations"), 'update'));
DROP POLICY IF EXISTS "khwarizmi_registrations_delete_frahoosh" ON public."khwarizmi_registrations";
CREATE POLICY "khwarizmi_registrations_delete_frahoosh" ON public."khwarizmi_registrations" FOR DELETE TO authenticated USING (private.frahoosh_can_access('khwarizmi_registrations', to_jsonb("khwarizmi_registrations"), 'delete'));
CREATE INDEX IF NOT EXISTS "khwarizmi_registrations_student_id_idx" ON public."khwarizmi_registrations" (student_id);
CREATE TABLE IF NOT EXISTS public."lesson_plans" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher_id" bigint,
  "teacher_name" text,
  "subject" text,
  "grade" text,
  "class_name" text,
  "title" text,
  "content" text,
  "session_date" text,
  "lesson_title" text,
  "description" text,
  "plan_date" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."lesson_plans" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."lesson_plans" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."lesson_plans_id_seq" TO authenticated;
DROP POLICY IF EXISTS "lesson_plans_select_frahoosh" ON public."lesson_plans";
CREATE POLICY "lesson_plans_select_frahoosh" ON public."lesson_plans" FOR SELECT TO authenticated USING (private.frahoosh_can_access('lesson_plans', to_jsonb("lesson_plans"), 'select'));
DROP POLICY IF EXISTS "lesson_plans_insert_frahoosh" ON public."lesson_plans";
CREATE POLICY "lesson_plans_insert_frahoosh" ON public."lesson_plans" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('lesson_plans', to_jsonb("lesson_plans"), 'insert'));
DROP POLICY IF EXISTS "lesson_plans_update_frahoosh" ON public."lesson_plans";
CREATE POLICY "lesson_plans_update_frahoosh" ON public."lesson_plans" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('lesson_plans', to_jsonb("lesson_plans"), 'update')) WITH CHECK (private.frahoosh_can_access('lesson_plans', to_jsonb("lesson_plans"), 'update'));
DROP POLICY IF EXISTS "lesson_plans_delete_frahoosh" ON public."lesson_plans";
CREATE POLICY "lesson_plans_delete_frahoosh" ON public."lesson_plans" FOR DELETE TO authenticated USING (private.frahoosh_can_access('lesson_plans', to_jsonb("lesson_plans"), 'delete'));
CREATE INDEX IF NOT EXISTS "lesson_plans_teacher_id_idx" ON public."lesson_plans" (teacher_id);
CREATE TABLE IF NOT EXISTS public."monthly_report_cards" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "month_name" text,
  "active" boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."monthly_report_cards" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."monthly_report_cards" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."monthly_report_cards_id_seq" TO authenticated;
DROP POLICY IF EXISTS "monthly_report_cards_select_frahoosh" ON public."monthly_report_cards";
CREATE POLICY "monthly_report_cards_select_frahoosh" ON public."monthly_report_cards" FOR SELECT TO authenticated USING (private.frahoosh_can_access('monthly_report_cards', to_jsonb("monthly_report_cards"), 'select'));
DROP POLICY IF EXISTS "monthly_report_cards_insert_frahoosh" ON public."monthly_report_cards";
CREATE POLICY "monthly_report_cards_insert_frahoosh" ON public."monthly_report_cards" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('monthly_report_cards', to_jsonb("monthly_report_cards"), 'insert'));
DROP POLICY IF EXISTS "monthly_report_cards_update_frahoosh" ON public."monthly_report_cards";
CREATE POLICY "monthly_report_cards_update_frahoosh" ON public."monthly_report_cards" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('monthly_report_cards', to_jsonb("monthly_report_cards"), 'update')) WITH CHECK (private.frahoosh_can_access('monthly_report_cards', to_jsonb("monthly_report_cards"), 'update'));
DROP POLICY IF EXISTS "monthly_report_cards_delete_frahoosh" ON public."monthly_report_cards";
CREATE POLICY "monthly_report_cards_delete_frahoosh" ON public."monthly_report_cards" FOR DELETE TO authenticated USING (private.frahoosh_can_access('monthly_report_cards', to_jsonb("monthly_report_cards"), 'delete'));
CREATE INDEX IF NOT EXISTS "monthly_report_cards_student_id_idx" ON public."monthly_report_cards" (student_id);
CREATE TABLE IF NOT EXISTS public."morning_ceremony" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ceremony_date" text,
  "title" text,
  "qari_name" text,
  "leader_name" text,
  "program" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."morning_ceremony" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."morning_ceremony" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."morning_ceremony_id_seq" TO authenticated;
DROP POLICY IF EXISTS "morning_ceremony_select_frahoosh" ON public."morning_ceremony";
CREATE POLICY "morning_ceremony_select_frahoosh" ON public."morning_ceremony" FOR SELECT TO authenticated USING (private.frahoosh_can_access('morning_ceremony', to_jsonb("morning_ceremony"), 'select'));
DROP POLICY IF EXISTS "morning_ceremony_insert_frahoosh" ON public."morning_ceremony";
CREATE POLICY "morning_ceremony_insert_frahoosh" ON public."morning_ceremony" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('morning_ceremony', to_jsonb("morning_ceremony"), 'insert'));
DROP POLICY IF EXISTS "morning_ceremony_update_frahoosh" ON public."morning_ceremony";
CREATE POLICY "morning_ceremony_update_frahoosh" ON public."morning_ceremony" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('morning_ceremony', to_jsonb("morning_ceremony"), 'update')) WITH CHECK (private.frahoosh_can_access('morning_ceremony', to_jsonb("morning_ceremony"), 'update'));
DROP POLICY IF EXISTS "morning_ceremony_delete_frahoosh" ON public."morning_ceremony";
CREATE POLICY "morning_ceremony_delete_frahoosh" ON public."morning_ceremony" FOR DELETE TO authenticated USING (private.frahoosh_can_access('morning_ceremony', to_jsonb("morning_ceremony"), 'delete'));
CREATE TABLE IF NOT EXISTS public."parent_activities" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text,
  "description" text,
  "activity_date" text,
  "status" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."parent_activities" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."parent_activities" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."parent_activities_id_seq" TO authenticated;
DROP POLICY IF EXISTS "parent_activities_select_frahoosh" ON public."parent_activities";
CREATE POLICY "parent_activities_select_frahoosh" ON public."parent_activities" FOR SELECT TO authenticated USING (private.frahoosh_can_access('parent_activities', to_jsonb("parent_activities"), 'select'));
DROP POLICY IF EXISTS "parent_activities_insert_frahoosh" ON public."parent_activities";
CREATE POLICY "parent_activities_insert_frahoosh" ON public."parent_activities" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('parent_activities', to_jsonb("parent_activities"), 'insert'));
DROP POLICY IF EXISTS "parent_activities_update_frahoosh" ON public."parent_activities";
CREATE POLICY "parent_activities_update_frahoosh" ON public."parent_activities" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('parent_activities', to_jsonb("parent_activities"), 'update')) WITH CHECK (private.frahoosh_can_access('parent_activities', to_jsonb("parent_activities"), 'update'));
DROP POLICY IF EXISTS "parent_activities_delete_frahoosh" ON public."parent_activities";
CREATE POLICY "parent_activities_delete_frahoosh" ON public."parent_activities" FOR DELETE TO authenticated USING (private.frahoosh_can_access('parent_activities', to_jsonb("parent_activities"), 'delete'));
CREATE TABLE IF NOT EXISTS public."parent_meeting_requests" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_id" bigint,
  "parent_name" text,
  "student_id" bigint,
  "student_name" text,
  "target_role" text,
  "target_name" text,
  "requested_date_shamsi" text,
  "requested_time" text,
  "reason" text,
  "status" text,
  "educational_approval" boolean NOT NULL DEFAULT false,
  "manager_approval" boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."parent_meeting_requests" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."parent_meeting_requests" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."parent_meeting_requests_id_seq" TO authenticated;
DROP POLICY IF EXISTS "parent_meeting_requests_select_frahoosh" ON public."parent_meeting_requests";
CREATE POLICY "parent_meeting_requests_select_frahoosh" ON public."parent_meeting_requests" FOR SELECT TO authenticated USING (private.frahoosh_can_access('parent_meeting_requests', to_jsonb("parent_meeting_requests"), 'select'));
DROP POLICY IF EXISTS "parent_meeting_requests_insert_frahoosh" ON public."parent_meeting_requests";
CREATE POLICY "parent_meeting_requests_insert_frahoosh" ON public."parent_meeting_requests" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('parent_meeting_requests', to_jsonb("parent_meeting_requests"), 'insert'));
DROP POLICY IF EXISTS "parent_meeting_requests_update_frahoosh" ON public."parent_meeting_requests";
CREATE POLICY "parent_meeting_requests_update_frahoosh" ON public."parent_meeting_requests" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('parent_meeting_requests', to_jsonb("parent_meeting_requests"), 'update')) WITH CHECK (private.frahoosh_can_access('parent_meeting_requests', to_jsonb("parent_meeting_requests"), 'update'));
DROP POLICY IF EXISTS "parent_meeting_requests_delete_frahoosh" ON public."parent_meeting_requests";
CREATE POLICY "parent_meeting_requests_delete_frahoosh" ON public."parent_meeting_requests" FOR DELETE TO authenticated USING (private.frahoosh_can_access('parent_meeting_requests', to_jsonb("parent_meeting_requests"), 'delete'));
CREATE INDEX IF NOT EXISTS "parent_meeting_requests_student_id_idx" ON public."parent_meeting_requests" (student_id);
CREATE TABLE IF NOT EXISTS public."school_class_config" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grade" text,
  "class_name" text,
  "teacher_id" bigint,
  "capacity" integer,
  "academic_year" text,
  "active" boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."school_class_config" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."school_class_config" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."school_class_config_id_seq" TO authenticated;
DROP POLICY IF EXISTS "school_class_config_select_frahoosh" ON public."school_class_config";
CREATE POLICY "school_class_config_select_frahoosh" ON public."school_class_config" FOR SELECT TO authenticated USING (private.frahoosh_can_access('school_class_config', to_jsonb("school_class_config"), 'select'));
DROP POLICY IF EXISTS "school_class_config_insert_frahoosh" ON public."school_class_config";
CREATE POLICY "school_class_config_insert_frahoosh" ON public."school_class_config" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('school_class_config', to_jsonb("school_class_config"), 'insert'));
DROP POLICY IF EXISTS "school_class_config_update_frahoosh" ON public."school_class_config";
CREATE POLICY "school_class_config_update_frahoosh" ON public."school_class_config" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('school_class_config', to_jsonb("school_class_config"), 'update')) WITH CHECK (private.frahoosh_can_access('school_class_config', to_jsonb("school_class_config"), 'update'));
DROP POLICY IF EXISTS "school_class_config_delete_frahoosh" ON public."school_class_config";
CREATE POLICY "school_class_config_delete_frahoosh" ON public."school_class_config" FOR DELETE TO authenticated USING (private.frahoosh_can_access('school_class_config', to_jsonb("school_class_config"), 'delete'));
CREATE INDEX IF NOT EXISTS "school_class_config_teacher_id_idx" ON public."school_class_config" (teacher_id);
CREATE TABLE IF NOT EXISTS public."student_cards" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "card_type" text,
  "code" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."student_cards" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."student_cards" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."student_cards_id_seq" TO authenticated;
DROP POLICY IF EXISTS "student_cards_select_frahoosh" ON public."student_cards";
CREATE POLICY "student_cards_select_frahoosh" ON public."student_cards" FOR SELECT TO authenticated USING (private.frahoosh_can_access('student_cards', to_jsonb("student_cards"), 'select'));
DROP POLICY IF EXISTS "student_cards_insert_frahoosh" ON public."student_cards";
CREATE POLICY "student_cards_insert_frahoosh" ON public."student_cards" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('student_cards', to_jsonb("student_cards"), 'insert'));
DROP POLICY IF EXISTS "student_cards_update_frahoosh" ON public."student_cards";
CREATE POLICY "student_cards_update_frahoosh" ON public."student_cards" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('student_cards', to_jsonb("student_cards"), 'update')) WITH CHECK (private.frahoosh_can_access('student_cards', to_jsonb("student_cards"), 'update'));
DROP POLICY IF EXISTS "student_cards_delete_frahoosh" ON public."student_cards";
CREATE POLICY "student_cards_delete_frahoosh" ON public."student_cards" FOR DELETE TO authenticated USING (private.frahoosh_can_access('student_cards', to_jsonb("student_cards"), 'delete'));
CREATE INDEX IF NOT EXISTS "student_cards_student_id_idx" ON public."student_cards" (student_id);
CREATE TABLE IF NOT EXISTS public."student_class_info" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "student_name" text,
  "grade" text,
  "class_name" text,
  "school_year" text,
  "classroom_seat" integer,
  "exam_seat" integer,
  "status" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."student_class_info" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."student_class_info" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."student_class_info_id_seq" TO authenticated;
DROP POLICY IF EXISTS "student_class_info_select_frahoosh" ON public."student_class_info";
CREATE POLICY "student_class_info_select_frahoosh" ON public."student_class_info" FOR SELECT TO authenticated USING (private.frahoosh_can_access('student_class_info', to_jsonb("student_class_info"), 'select'));
DROP POLICY IF EXISTS "student_class_info_insert_frahoosh" ON public."student_class_info";
CREATE POLICY "student_class_info_insert_frahoosh" ON public."student_class_info" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('student_class_info', to_jsonb("student_class_info"), 'insert'));
DROP POLICY IF EXISTS "student_class_info_update_frahoosh" ON public."student_class_info";
CREATE POLICY "student_class_info_update_frahoosh" ON public."student_class_info" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('student_class_info', to_jsonb("student_class_info"), 'update')) WITH CHECK (private.frahoosh_can_access('student_class_info', to_jsonb("student_class_info"), 'update'));
DROP POLICY IF EXISTS "student_class_info_delete_frahoosh" ON public."student_class_info";
CREATE POLICY "student_class_info_delete_frahoosh" ON public."student_class_info" FOR DELETE TO authenticated USING (private.frahoosh_can_access('student_class_info', to_jsonb("student_class_info"), 'delete'));
CREATE INDEX IF NOT EXISTS "student_class_info_student_id_idx" ON public."student_class_info" (student_id);
CREATE TABLE IF NOT EXISTS public."student_referrals" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" bigint,
  "teacher_id" bigint,
  "referral_to" text,
  "reason" text,
  "referral_date" text,
  "status" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."student_referrals" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."student_referrals" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."student_referrals_id_seq" TO authenticated;
DROP POLICY IF EXISTS "student_referrals_select_frahoosh" ON public."student_referrals";
CREATE POLICY "student_referrals_select_frahoosh" ON public."student_referrals" FOR SELECT TO authenticated USING (private.frahoosh_can_access('student_referrals', to_jsonb("student_referrals"), 'select'));
DROP POLICY IF EXISTS "student_referrals_insert_frahoosh" ON public."student_referrals";
CREATE POLICY "student_referrals_insert_frahoosh" ON public."student_referrals" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('student_referrals', to_jsonb("student_referrals"), 'insert'));
DROP POLICY IF EXISTS "student_referrals_update_frahoosh" ON public."student_referrals";
CREATE POLICY "student_referrals_update_frahoosh" ON public."student_referrals" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('student_referrals', to_jsonb("student_referrals"), 'update')) WITH CHECK (private.frahoosh_can_access('student_referrals', to_jsonb("student_referrals"), 'update'));
DROP POLICY IF EXISTS "student_referrals_delete_frahoosh" ON public."student_referrals";
CREATE POLICY "student_referrals_delete_frahoosh" ON public."student_referrals" FOR DELETE TO authenticated USING (private.frahoosh_can_access('student_referrals', to_jsonb("student_referrals"), 'delete'));
CREATE INDEX IF NOT EXISTS "student_referrals_student_id_idx" ON public."student_referrals" (student_id);
CREATE INDEX IF NOT EXISTS "student_referrals_teacher_id_idx" ON public."student_referrals" (teacher_id);
CREATE TABLE IF NOT EXISTS public."survey_responses" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "survey_id" bigint,
  "respondent_username" text,
  "respondent_role" text,
  "student_id" bigint,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."survey_responses" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."survey_responses" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."survey_responses_id_seq" TO authenticated;
DROP POLICY IF EXISTS "survey_responses_select_frahoosh" ON public."survey_responses";
CREATE POLICY "survey_responses_select_frahoosh" ON public."survey_responses" FOR SELECT TO authenticated USING (private.frahoosh_can_access('survey_responses', to_jsonb("survey_responses"), 'select'));
DROP POLICY IF EXISTS "survey_responses_insert_frahoosh" ON public."survey_responses";
CREATE POLICY "survey_responses_insert_frahoosh" ON public."survey_responses" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('survey_responses', to_jsonb("survey_responses"), 'insert'));
DROP POLICY IF EXISTS "survey_responses_update_frahoosh" ON public."survey_responses";
CREATE POLICY "survey_responses_update_frahoosh" ON public."survey_responses" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('survey_responses', to_jsonb("survey_responses"), 'update')) WITH CHECK (private.frahoosh_can_access('survey_responses', to_jsonb("survey_responses"), 'update'));
DROP POLICY IF EXISTS "survey_responses_delete_frahoosh" ON public."survey_responses";
CREATE POLICY "survey_responses_delete_frahoosh" ON public."survey_responses" FOR DELETE TO authenticated USING (private.frahoosh_can_access('survey_responses', to_jsonb("survey_responses"), 'delete'));
CREATE INDEX IF NOT EXISTS "survey_responses_student_id_idx" ON public."survey_responses" (student_id);
CREATE TABLE IF NOT EXISTS public."surveys" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text,
  "description" text,
  "status" text,
  "audience" text,
  "start_at" text,
  "end_at" text,
  "created_by" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."surveys" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."surveys" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."surveys_id_seq" TO authenticated;
DROP POLICY IF EXISTS "surveys_select_frahoosh" ON public."surveys";
CREATE POLICY "surveys_select_frahoosh" ON public."surveys" FOR SELECT TO authenticated USING (private.frahoosh_can_access('surveys', to_jsonb("surveys"), 'select'));
DROP POLICY IF EXISTS "surveys_insert_frahoosh" ON public."surveys";
CREATE POLICY "surveys_insert_frahoosh" ON public."surveys" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('surveys', to_jsonb("surveys"), 'insert'));
DROP POLICY IF EXISTS "surveys_update_frahoosh" ON public."surveys";
CREATE POLICY "surveys_update_frahoosh" ON public."surveys" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('surveys', to_jsonb("surveys"), 'update')) WITH CHECK (private.frahoosh_can_access('surveys', to_jsonb("surveys"), 'update'));
DROP POLICY IF EXISTS "surveys_delete_frahoosh" ON public."surveys";
CREATE POLICY "surveys_delete_frahoosh" ON public."surveys" FOR DELETE TO authenticated USING (private.frahoosh_can_access('surveys', to_jsonb("surveys"), 'delete'));
CREATE TABLE IF NOT EXISTS public."transport_requests" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_username" text,
  "address" text,
  "vehicle_type" text,
  "origin" text,
  "destination" text,
  "note" text,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public."transport_requests" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."transport_requests" TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public."transport_requests_id_seq" TO authenticated;
DROP POLICY IF EXISTS "transport_requests_select_frahoosh" ON public."transport_requests";
CREATE POLICY "transport_requests_select_frahoosh" ON public."transport_requests" FOR SELECT TO authenticated USING (private.frahoosh_can_access('transport_requests', to_jsonb("transport_requests"), 'select'));
DROP POLICY IF EXISTS "transport_requests_insert_frahoosh" ON public."transport_requests";
CREATE POLICY "transport_requests_insert_frahoosh" ON public."transport_requests" FOR INSERT TO authenticated WITH CHECK (private.frahoosh_can_access('transport_requests', to_jsonb("transport_requests"), 'insert'));
DROP POLICY IF EXISTS "transport_requests_update_frahoosh" ON public."transport_requests";
CREATE POLICY "transport_requests_update_frahoosh" ON public."transport_requests" FOR UPDATE TO authenticated USING (private.frahoosh_can_access('transport_requests', to_jsonb("transport_requests"), 'update')) WITH CHECK (private.frahoosh_can_access('transport_requests', to_jsonb("transport_requests"), 'update'));
DROP POLICY IF EXISTS "transport_requests_delete_frahoosh" ON public."transport_requests";
CREATE POLICY "transport_requests_delete_frahoosh" ON public."transport_requests" FOR DELETE TO authenticated USING (private.frahoosh_can_access('transport_requests', to_jsonb("transport_requests"), 'delete'));
